/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     http://www.apache.org/licenses/LICENSE-2.0
/// 
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 0x1000004b generated on 2026-06-09 09:19:39.976906
/// Generated using solver translation3d
/// To compile with gcc:
///     gcc -lstdc++ ik.cpp
/// To compile without any main function as a shared object (might need -llapack):
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp
#define IKFAST_HAS_LIBRARY
#include "ikfast.h" // found inside share/openrave-X.Y/python/ikfast.h
using namespace ikfast;

// check if the included ikfast version matches what this file was compiled with
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
IKFAST_COMPILE_ASSERT(IKFAST_VERSION==0x1000004b);

#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>

#ifndef IKFAST_ASSERT
#include <stdexcept>
#include <sstream>
#include <iostream>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI  ((IkReal)6.28318530717959)
#define IKPI  ((IkReal)3.14159265358979)
#define IKPI_2  ((IkReal)1.57079632679490)

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#ifndef isinf
#define isinf _isinf
#endif
//#ifndef isfinite
//#define isfinite _isfinite
//#endif
#endif // _MSC_VER

// lapack routines
extern "C" {
  void dgetrf_ (const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
  void zgetrf_ (const int* m, const int* n, std::complex<double>* a, const int* lda, int* ipiv, int* info);
  void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
  void dgesv_ (const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
  void dgetrs_(const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info);
  void dgeev_(const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi,double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info);
}

using namespace std; // necessary to get std math routines

#ifdef IKFAST_NAMESPACE
namespace IKFAST_NAMESPACE {
#endif

inline float IKabs(float f) { return fabsf(f); }
inline double IKabs(double f) { return fabs(f); }

inline float IKsqr(float f) { return f*f; }
inline double IKsqr(double f) { return f*f; }

inline float IKlog(float f) { return logf(f); }
inline double IKlog(double f) { return log(f); }

// allows asin and acos to exceed 1. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_SINCOS_THRESH
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
#endif

// used to check input to atan2 for degenerate cases. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_ATAN2_MAGTHRESH
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
#endif

// minimum distance of separate solutions
#ifndef IKFAST_SOLUTION_THRESH
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#endif

// there are checkpoints in ikfast that are evaluated to make sure they are 0. This threshold speicfies by how much they can deviate
#ifndef IKFAST_EVALCOND_THRESH
#define IKFAST_EVALCOND_THRESH ((IkReal)0.03) // 5D IK has some crazy degenerate cases, but can rely on jacobian refinment to make better, just need good starting point
#endif


inline float IKasin(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(-IKPI_2);
else if( f >= 1 ) return float(IKPI_2);
return asinf(f);
}
inline double IKasin(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asin(f);
}

// return positive value in [0,y)
inline float IKfmod(float x, float y)
{
    while(x < 0) {
        x += y;
    }
    return fmodf(x,y);
}

// return positive value in [0,y)
inline double IKfmod(double x, double y)
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}

inline float IKacos(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(IKPI);
else if( f >= 1 ) return float(0);
return acosf(f);
}
inline double IKacos(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0;
return acos(f);
}
inline float IKsin(float f) { return sinf(f); }
inline double IKsin(double f) { return sin(f); }
inline float IKcos(float f) { return cosf(f); }
inline double IKcos(double f) { return cos(f); }
inline float IKtan(float f) { return tanf(f); }
inline double IKtan(double f) { return tan(f); }
inline float IKsqrt(float f) { if( f <= 0.0f ) return 0.0f; return sqrtf(f); }
inline double IKsqrt(double f) { if( f <= 0.0 ) return 0.0; return sqrt(f); }
inline float IKatan2Simple(float fy, float fx) {
    return atan2f(fy,fx);
}
inline float IKatan2(float fy, float fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return float(IKPI_2);
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2f(fy,fx);
}
inline double IKatan2Simple(double fy, double fx) {
    return atan2(fy,fx);
}
inline double IKatan2(double fy, double fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2(fy,fx);
}

template <typename T>
struct CheckValue
{
    T value;
    bool valid;
};

template <typename T>
inline CheckValue<T> IKatan2WithCheck(T fy, T fx, T epsilon)
{
    CheckValue<T> ret;
    ret.valid = false;
    ret.value = 0;
    if( !isnan(fy) && !isnan(fx) ) {
        if( IKabs(fy) >= IKFAST_ATAN2_MAGTHRESH || IKabs(fx) > IKFAST_ATAN2_MAGTHRESH ) {
            ret.value = IKatan2Simple(fy,fx);
            ret.valid = true;
        }
    }
    return ret;
}

inline float IKsign(float f) {
    if( f > 0 ) {
        return float(1);
    }
    else if( f < 0 ) {
        return float(-1);
    }
    return 0;
}

inline double IKsign(double f) {
    if( f > 0 ) {
        return 1.0;
    }
    else if( f < 0 ) {
        return -1.0;
    }
    return 0;
}

template <typename T>
inline CheckValue<T> IKPowWithIntegerCheck(T f, int n)
{
    CheckValue<T> ret;
    ret.valid = true;
    if( n == 0 ) {
        ret.value = 1.0;
        return ret;
    }
    else if( n == 1 )
    {
        ret.value = f;
        return ret;
    }
    else if( n < 0 )
    {
        if( f == 0 )
        {
            ret.valid = false;
            ret.value = (T)1.0e30;
            return ret;
        }
        if( n == -1 ) {
            ret.value = T(1.0)/f;
            return ret;
        }
    }

    int num = n > 0 ? n : -n;
    if( num == 2 ) {
        ret.value = f*f;
    }
    else if( num == 3 ) {
        ret.value = f*f*f;
    }
    else {
        ret.value = 1.0;
        while(num>0) {
            if( num & 1 ) {
                ret.value *= f;
            }
            num >>= 1;
            f *= f;
        }
    }
    
    if( n < 0 ) {
        ret.value = T(1.0)/ret.value;
    }
    return ret;
}

template <typename T> struct ComplexLess
{
    bool operator()(const complex<T>& lhs, const complex<T>& rhs) const
    {
        if (real(lhs) < real(rhs)) {
            return true;
        }
        if (real(lhs) > real(rhs)) {
            return false;
        }
        return imag(lhs) < imag(rhs);
    }
};

/// solves the forward kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void ComputeFk(const IkReal* j, IkReal* eetrans, IkReal* eerot) {
IkReal x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15;
x0=IKcos(j[0]);
x1=IKcos(j[1]);
x2=IKcos(j[2]);
x3=IKsin(j[1]);
x4=IKsin(j[2]);
x5=IKsin(j[0]);
x6=((0.00200103)*x2);
x7=((0.28019999)*x1);
x8=((0.28019999)*x2);
x9=((0.28019999)*x4);
x10=((0.00200103)*x4);
x11=(x3*x5);
x12=(x1*x5);
x13=(x0*x4);
x14=(x0*x3);
x15=(x0*x1);
eetrans[0]=(((x14*x8))+(((-1.0)*x10*x14))+(((0.236820144868803)*x14))+((x13*x7))+(((0.02999885)*x15))+((x15*x6)));
eetrans[1]=(((x4*x5*x7))+((x11*x8))+(((-1.0)*x10*x11))+((x12*x6))+(((0.236820144868803)*x11))+(((0.02999885)*x12)));
IkReal x16=((1.0)*x3);
eetrans[2]=((0.088)+(((-1.0)*x1*x10))+((x2*x7))+(((-1.0)*x16*x9))+(((-1.0)*x16*x6))+(((-0.02999885)*x3))+(((0.236820144868803)*x1)));
}

IKFAST_API int GetNumFreeParameters() { return 0; }
IKFAST_API int* GetFreeParameters() { return NULL; }
IKFAST_API const int* GetFreeIndices() { return NULL; }
IKFAST_API int GetNumJoints() { return 3; }

IKFAST_API int GetIkRealSize() { return sizeof(IkReal); }

IKFAST_API int GetIkType() { return 0x33000003; }

class IKSolver {
public:
IkReal j4,cj4,sj4,htj4,j4mul,j5,cj5,sj5,htj5,j5mul,j6,cj6,sj6,htj6,j6mul,new_px,px,npx,new_py,py,npy,new_pz,pz,npz,pp;
unsigned char _ij4[2], _nj4,_ij5[2], _nj5,_ij6[2], _nj6;

IkReal j100, cj100, sj100;
unsigned char _ij100[2], _nj100;
bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
j4=numeric_limits<IkReal>::quiet_NaN(); _ij4[0] = -1; _ij4[1] = -1; _nj4 = -1; j5=numeric_limits<IkReal>::quiet_NaN(); _ij5[0] = -1; _ij5[1] = -1; _nj5 = -1; j6=numeric_limits<IkReal>::quiet_NaN(); _ij6[0] = -1; _ij6[1] = -1; _nj6 = -1; 
for(int dummyiter = 0; dummyiter < 1; ++dummyiter) {
    solutions.Clear();
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];

new_px=px;
new_py=py;
new_pz=((-0.088)+pz);
px = new_px; py = new_py; pz = new_pz;
pp=((px*px)+(py*py)+(pz*pz));
{
IkReal j6array[2], cj6array[2], sj6array[2];
bool j6valid[2]={false};
_nj6 = 2;
if( (((-1.0128705456968)+(((7.47507314002149)*(pz*pz)))+(((7.47507314002149)*(px*px)))+(((7.47507314002149)*(py*py))))) < -1-IKFAST_SINCOS_THRESH || (((-1.0128705456968)+(((7.47507314002149)*(pz*pz)))+(((7.47507314002149)*(px*px)))+(((7.47507314002149)*(py*py))))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x17=IKasin(((-1.0128705456968)+(((7.47507314002149)*(pz*pz)))+(((7.47507314002149)*(px*px)))+(((7.47507314002149)*(py*py)))));
j6array[0]=((-1.45193517715052)+(((1.0)*x17)));
sj6array[0]=IKsin(j6array[0]);
cj6array[0]=IKcos(j6array[0]);
j6array[1]=((1.68965747643928)+(((-1.0)*x17)));
sj6array[1]=IKsin(j6array[1]);
cj6array[1]=IKcos(j6array[1]);
if( j6array[0] > IKPI )
{
    j6array[0]-=IK2PI;
}
else if( j6array[0] < -IKPI )
{    j6array[0]+=IK2PI;
}
j6valid[0] = true;
if( j6array[1] > IKPI )
{
    j6array[1]-=IK2PI;
}
else if( j6array[1] < -IKPI )
{    j6array[1]+=IK2PI;
}
j6valid[1] = true;
for(int ij6 = 0; ij6 < 2; ++ij6)
{
if( !j6valid[ij6] )
{
    continue;
}
_ij6[0] = ij6; _ij6[1] = -1;
for(int iij6 = ij6+1; iij6 < 2; ++iij6)
{
if( j6valid[iij6] && IKabs(cj6array[ij6]-cj6array[iij6]) < IKFAST_SOLUTION_THRESH && IKabs(sj6array[ij6]-sj6array[iij6]) < IKFAST_SOLUTION_THRESH )
{
    j6valid[iij6]=false; _ij6[1] = iij6; break; 
}
}
j6 = j6array[ij6]; cj6 = cj6array[ij6]; sj6 = sj6array[ij6];

{
IkReal j4eval[1];
j4eval[0]=((IKabs(px))+(IKabs(py)));
if( IKabs(j4eval[0]) < 0.0000010000000000  )
{
{
IkReal j5eval[1];
j5eval[0]=((3.59210774797445)+(((4.94945064676092)*(cj6*cj6)))+sj6+(((4.94945064676092)*(sj6*sj6)))+(((8.37352017169531)*cj6)));
if( IKabs(j5eval[0]) < 0.0000010000000000  )
{
{
IkReal evalcond[1];
bool bgotonextstatement = true;
do
{
evalcond[0]=((IKabs(px))+(IKabs(py)));
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j5eval[3];
px=0;
py=0;
pp=pz*pz;
j5eval[0]=pz;
j5eval[1]=((3.59210774797445)+(((4.94945064676092)*(cj6*cj6)))+sj6+(((4.94945064676092)*(sj6*sj6)))+(((8.37352017169531)*cj6)));
j5eval[2]=IKsign(pz);
if( IKabs(j5eval[0]) < 0.0000010000000000  || IKabs(j5eval[1]) < 0.0000010000000000  || IKabs(j5eval[2]) < 0.0000010000000000  )
{
{
IkReal j5eval[1];
px=0;
py=0;
pp=pz*pz;
j5eval[0]=pz;
if( IKabs(j5eval[0]) < 0.0000010000000000  )
{
{
IkReal j5eval[2];
px=0;
py=0;
pp=pz*pz;
j5eval[0]=pz;
j5eval[1]=(((cj6*pz))+(((14.9917042722998)*pz))+(((140.02788064147)*pz*sj6)));
if( IKabs(j5eval[0]) < 0.0000010000000000  || IKabs(j5eval[1]) < 0.0000010000000000  )
{
{
IkReal evalcond[1];
bool bgotonextstatement = true;
do
{
IkReal x18=pz*pz;
IkReal x19=IKabs(pz);
IkReal x20=x18;
CheckValue<IkReal> x26=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*x19)),-1);
if(!x26.valid){
continue;
}
IkReal x21=x26.value;
IkReal x27 = x20;
if(IKabs(x27)==0){
continue;
}
IkReal x22=pow(x27,-0.5);
CheckValue<IkReal> x28=IKPowWithIntegerCheck(x19,-2);
if(!x28.valid){
continue;
}
if((((1.0)+(((-0.0114617474126251)*x18*(x28.value))))) < -0.00001)
continue;
IkReal x23=IKsqrt(((1.0)+(((-0.0114617474126251)*x18*(x28.value)))));
IkReal x24=(x18*x21*x22);
IkReal x25=(pz*x22*x23);
if((x20) < -0.00001)
continue;
CheckValue<IkReal> x29=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x20)))),-1);
if(!x29.valid){
continue;
}
if( (((2999885.0)*pz*(x29.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x29.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
CheckValue<IkReal> x30 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x30.valid){
continue;
}
IkReal gconst0=((((-1.0)*(IKasin(((2999885.0)*pz*(x29.value))))))+(((-1.0)*(x30.value))));
IkReal gconst1=((((-2999808.50571881)*x24))+(((-0.00714125284441861)*x25)));
IkReal gconst2=((((-21422.9372891787)*x24))+(((0.999974500928805)*x25)));
CheckValue<IkReal> x31 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x31.valid){
continue;
}
if((pz*pz) < -0.00001)
continue;
CheckValue<IkReal> x32=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(pz*pz)))),-1);
if(!x32.valid){
continue;
}
if( (((2999885.0)*pz*(x32.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x32.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
evalcond[0]=((-3.14159265358979)+(IKfmod(((3.14159265358979)+(IKabs(((x31.value)+(IKasin(((2999885.0)*pz*(x32.value))))+j6)))), 6.28318530717959)));
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j5eval[2];
IkReal x33=pz*pz;
IkReal x34=IKabs(pz);
IkReal x35=x33;
IkReal x36=x21;
IkReal x42 = x35;
if(IKabs(x42)==0){
continue;
}
IkReal x37=pow(x42,-0.5);
IkReal x38=x23;
if((x35) < -0.00001)
continue;
CheckValue<IkReal> x43=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x35)))),-1);
if(!x43.valid){
continue;
}
if( (((2999885.0)*pz*(x43.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x43.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x39=((1.0)*(IKasin(((2999885.0)*pz*(x43.value)))));
IkReal x40=(x33*x36*x37);
IkReal x41=(pz*x37*x38);
px=0;
py=0;
pp=x33;
sj6=gconst1;
cj6=gconst2;
CheckValue<IkReal> x44 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x44.valid){
continue;
}
j6=((((-1.0)*x39))+(((-1.0)*(x44.value))));
CheckValue<IkReal> x45 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x45.valid){
continue;
}
IkReal gconst0=((((-1.0)*(x45.value)))+(((-1.0)*x39)));
IkReal gconst1=((((-2999808.50571881)*x40))+(((-0.00714125284441861)*x41)));
IkReal gconst2=((((0.999974500928805)*x41))+(((-21422.9372891787)*x40)));
j5eval[0]=pz;
j5eval[1]=IKsign(pz);
if( IKabs(j5eval[0]) < 0.0000010000000000  || IKabs(j5eval[1]) < 0.0000010000000000  )
{
{
IkReal j5eval[1];
IkReal x46=pz*pz;
IkReal x47=IKabs(pz);
IkReal x48=x46;
IkReal x49=x21;
IkReal x55 = x48;
if(IKabs(x55)==0){
continue;
}
IkReal x50=pow(x55,-0.5);
IkReal x51=x23;
if((x48) < -0.00001)
continue;
CheckValue<IkReal> x56=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x48)))),-1);
if(!x56.valid){
continue;
}
if( (((2999885.0)*pz*(x56.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x56.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x52=((1.0)*(IKasin(((2999885.0)*pz*(x56.value)))));
IkReal x53=(x46*x49*x50);
IkReal x54=(pz*x50*x51);
px=0;
py=0;
pp=x46;
sj6=gconst1;
cj6=gconst2;
CheckValue<IkReal> x57 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x57.valid){
continue;
}
j6=((((-1.0)*(x57.value)))+(((-1.0)*x52)));
CheckValue<IkReal> x58 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x58.valid){
continue;
}
IkReal gconst0=((((-1.0)*(x58.value)))+(((-1.0)*x52)));
IkReal gconst1=((((-2999808.50571881)*x53))+(((-0.00714125284441861)*x54)));
IkReal gconst2=((((-21422.9372891787)*x53))+(((0.999974500928805)*x54)));
j5eval[0]=pz;
if( IKabs(j5eval[0]) < 0.0000010000000000  )
{
{
IkReal j5eval[1];
IkReal x59=pz*pz;
IkReal x60=IKabs(pz);
IkReal x61=x59;
IkReal x62=x21;
IkReal x68 = x61;
if(IKabs(x68)==0){
continue;
}
IkReal x63=pow(x68,-0.5);
IkReal x64=x23;
if((x61) < -0.00001)
continue;
CheckValue<IkReal> x69=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x61)))),-1);
if(!x69.valid){
continue;
}
if( (((2999885.0)*pz*(x69.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x69.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x65=((1.0)*(IKasin(((2999885.0)*pz*(x69.value)))));
IkReal x66=(x59*x62*x63);
IkReal x67=(pz*x63*x64);
px=0;
py=0;
pp=x59;
sj6=gconst1;
cj6=gconst2;
CheckValue<IkReal> x70 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x70.valid){
continue;
}
j6=((((-1.0)*(x70.value)))+(((-1.0)*x65)));
CheckValue<IkReal> x71 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x71.valid){
continue;
}
IkReal gconst0=((((-1.0)*(x71.value)))+(((-1.0)*x65)));
IkReal gconst1=((((-2999808.50571881)*x66))+(((-0.00714125284441861)*x67)));
IkReal gconst2=((((0.999974500928805)*x67))+(((-21422.9372891787)*x66)));
j5eval[0]=pz;
if( IKabs(j5eval[0]) < 0.0000010000000000  )
{
continue; // no branches [j4, j5]

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
CheckValue<IkReal> x72=IKPowWithIntegerCheck(pz,-1);
if(!x72.valid){
continue;
}
CheckValue<IkReal> x73=IKPowWithIntegerCheck(((((-0.28019999)*gconst2*pz))+(((0.00200103)*gconst1*pz))+(((-0.236820144868803)*pz))),-1);
if(!x73.valid){
continue;
}
if( IKabs(((x72.value)*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((x73.value)*(((0.0008999310013225)+(((0.0785120343960001)*(gconst1*gconst1)))+(((-1.0)*(pz*pz)))+(((0.000120057197631)*gconst2))+(((0.0011213771719794)*gconst1*gconst2))+(((4.0041210609e-6)*(gconst2*gconst2)))+(((0.016811354940023)*gconst1)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr(((x72.value)*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1))))))+IKsqr(((x73.value)*(((0.0008999310013225)+(((0.0785120343960001)*(gconst1*gconst1)))+(((-1.0)*(pz*pz)))+(((0.000120057197631)*gconst2))+(((0.0011213771719794)*gconst1*gconst2))+(((4.0041210609e-6)*(gconst2*gconst2)))+(((0.016811354940023)*gconst1))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j5array[0]=IKatan2(((x72.value)*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1))))), ((x73.value)*(((0.0008999310013225)+(((0.0785120343960001)*(gconst1*gconst1)))+(((-1.0)*(pz*pz)))+(((0.000120057197631)*gconst2))+(((0.0011213771719794)*gconst1*gconst2))+(((4.0041210609e-6)*(gconst2*gconst2)))+(((0.016811354940023)*gconst1))))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x74=IKcos(j5);
IkReal x75=IKsin(j5);
IkReal x76=((0.28019999)*gconst2);
IkReal x77=((0.00200103)*gconst2);
IkReal x78=((0.28019999)*gconst1);
IkReal x79=((0.00200103)*gconst1);
IkReal x80=((0.28019999)*x74);
IkReal x81=(pz*x75);
IkReal x82=(pz*x74);
evalcond[0]=((0.02999885)+x77+x78+x81);
evalcond[1]=((0.236820144868803)+(((-1.0)*x79))+x76+(((-1.0)*x82)));
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x81))+(((0.473640289737606)*x82))+(((-1.0)*(pz*pz))));
evalcond[3]=((((0.236820144868803)*x75))+((x75*x76))+(((0.02999885)*x74))+((x74*x77))+((x74*x78))+(((-1.0)*x75*x79)));
evalcond[4]=(((x75*x77))+((x75*x78))+(((-1.0)*x74*x76))+pz+(((-0.236820144868803)*x74))+(((0.02999885)*x75))+((x74*x79)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
CheckValue<IkReal> x84=IKPowWithIntegerCheck(pz,-1);
if(!x84.valid){
continue;
}
IkReal x83=x84.value;
CheckValue<IkReal> x85=IKPowWithIntegerCheck(x83,-2);
if(!x85.valid){
continue;
}
if( IKabs((x83*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((6.25e-14)*x83*(((-788182559912.831)+(((-4055641388.02502)*gconst2))+(((33780910000000.0)*(x85.value)))+(((-567902868206.972)*gconst1)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr((x83*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1))))))+IKsqr(((6.25e-14)*x83*(((-788182559912.831)+(((-4055641388.02502)*gconst2))+(((33780910000000.0)*(x85.value)))+(((-567902868206.972)*gconst1))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j5array[0]=IKatan2((x83*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1))))), ((6.25e-14)*x83*(((-788182559912.831)+(((-4055641388.02502)*gconst2))+(((33780910000000.0)*(x85.value)))+(((-567902868206.972)*gconst1))))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x86=IKcos(j5);
IkReal x87=IKsin(j5);
IkReal x88=((0.28019999)*gconst2);
IkReal x89=((0.00200103)*gconst2);
IkReal x90=((0.28019999)*gconst1);
IkReal x91=((0.00200103)*gconst1);
IkReal x92=((0.28019999)*x86);
IkReal x93=(pz*x87);
IkReal x94=(pz*x86);
evalcond[0]=((0.02999885)+x89+x90+x93);
evalcond[1]=((0.236820144868803)+x88+(((-1.0)*x94))+(((-1.0)*x91)));
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x93))+(((0.473640289737606)*x94))+(((-1.0)*(pz*pz))));
evalcond[3]=(((x86*x90))+(((0.236820144868803)*x87))+((x86*x89))+(((0.02999885)*x86))+(((-1.0)*x87*x91))+((x87*x88)));
evalcond[4]=(((x87*x90))+((x86*x91))+(((-1.0)*x86*x88))+(((0.02999885)*x87))+pz+(((-0.236820144868803)*x86))+((x87*x89)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
CheckValue<IkReal> x95 = IKatan2WithCheck(IkReal(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1)))),IkReal(((0.236820144868803)+(((-0.00200103)*gconst1))+(((0.28019999)*gconst2)))),IKFAST_ATAN2_MAGTHRESH);
if(!x95.valid){
continue;
}
CheckValue<IkReal> x96=IKPowWithIntegerCheck(IKsign(pz),-1);
if(!x96.valid){
continue;
}
j5array[0]=((-1.5707963267949)+(x95.value)+(((1.5707963267949)*(x96.value))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x97=IKcos(j5);
IkReal x98=IKsin(j5);
IkReal x99=((0.28019999)*gconst2);
IkReal x100=((0.00200103)*gconst2);
IkReal x101=((0.28019999)*gconst1);
IkReal x102=((0.00200103)*gconst1);
IkReal x103=((0.28019999)*x97);
IkReal x104=(pz*x98);
IkReal x105=(pz*x97);
evalcond[0]=((0.02999885)+x104+x100+x101);
evalcond[1]=((0.236820144868803)+(((-1.0)*x102))+x99+(((-1.0)*x105)));
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x104))+(((-1.0)*(pz*pz)))+(((0.473640289737606)*x105)));
evalcond[3]=((((-1.0)*x102*x98))+((x100*x97))+((x101*x97))+(((0.236820144868803)*x98))+(((0.02999885)*x97))+((x98*x99)));
evalcond[4]=(((x100*x98))+((x102*x97))+((x101*x98))+(((0.02999885)*x98))+pz+(((-0.236820144868803)*x97))+(((-1.0)*x97*x99)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
IkReal x106=pz*pz;
IkReal x107=IKabs(pz);
IkReal x108=x106;
CheckValue<IkReal> x114=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*x107)),-1);
if(!x114.valid){
continue;
}
IkReal x109=x114.value;
IkReal x115 = x108;
if(IKabs(x115)==0){
continue;
}
IkReal x110=pow(x115,-0.5);
CheckValue<IkReal> x116=IKPowWithIntegerCheck(x107,-2);
if(!x116.valid){
continue;
}
if((((1.0)+(((-0.0114617474126251)*x106*(x116.value))))) < -0.00001)
continue;
IkReal x111=IKsqrt(((1.0)+(((-0.0114617474126251)*x106*(x116.value)))));
IkReal x112=(x106*x109*x110);
IkReal x113=(pz*x110*x111);
CheckValue<IkReal> x117 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x117.valid){
continue;
}
if((x108) < -0.00001)
continue;
CheckValue<IkReal> x118=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x108)))),-1);
if(!x118.valid){
continue;
}
if( (((2999885.0)*pz*(x118.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x118.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal gconst3=((3.14159265358979)+(((-1.0)*(x117.value)))+(IKasin(((2999885.0)*pz*(x118.value)))));
IkReal gconst4=((((-2999808.50571881)*x112))+(((0.00714125284441861)*x113)));
IkReal gconst5=((((-21422.9372891787)*x112))+(((-0.999974500928805)*x113)));
CheckValue<IkReal> x119 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x119.valid){
continue;
}
if((pz*pz) < -0.00001)
continue;
CheckValue<IkReal> x120=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(pz*pz)))),-1);
if(!x120.valid){
continue;
}
if( (((2999885.0)*pz*(x120.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x120.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
evalcond[0]=((-3.14159265358979)+(IKfmod(((3.14159265358979)+(IKabs(((-3.14159265358979)+(x119.value)+(((-1.0)*(IKasin(((2999885.0)*pz*(x120.value))))))+j6)))), 6.28318530717959)));
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j5eval[2];
IkReal x121=pz*pz;
IkReal x122=IKabs(pz);
IkReal x123=x121;
IkReal x124=x109;
IkReal x130 = x123;
if(IKabs(x130)==0){
continue;
}
IkReal x125=pow(x130,-0.5);
IkReal x126=x111;
if((x123) < -0.00001)
continue;
CheckValue<IkReal> x131=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x123)))),-1);
if(!x131.valid){
continue;
}
if( (((2999885.0)*pz*(x131.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x131.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x127=IKasin(((2999885.0)*pz*(x131.value)));
IkReal x128=(x121*x124*x125);
IkReal x129=(pz*x125*x126);
px=0;
py=0;
pp=x121;
sj6=gconst4;
cj6=gconst5;
CheckValue<IkReal> x132 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x132.valid){
continue;
}
j6=((3.14159265)+x127+(((-1.0)*(x132.value))));
CheckValue<IkReal> x133 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x133.valid){
continue;
}
IkReal gconst3=((3.14159265358979)+(((-1.0)*(x133.value)))+x127);
IkReal gconst4=((((-2999808.50571881)*x128))+(((0.00714125284441861)*x129)));
IkReal gconst5=((((-21422.9372891787)*x128))+(((-0.999974500928805)*x129)));
j5eval[0]=pz;
j5eval[1]=IKsign(pz);
if( IKabs(j5eval[0]) < 0.0000010000000000  || IKabs(j5eval[1]) < 0.0000010000000000  )
{
{
IkReal j5eval[1];
IkReal x134=pz*pz;
IkReal x135=IKabs(pz);
IkReal x136=x134;
IkReal x137=x109;
IkReal x143 = x136;
if(IKabs(x143)==0){
continue;
}
IkReal x138=pow(x143,-0.5);
IkReal x139=x111;
if((x136) < -0.00001)
continue;
CheckValue<IkReal> x144=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x136)))),-1);
if(!x144.valid){
continue;
}
if( (((2999885.0)*pz*(x144.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x144.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x140=IKasin(((2999885.0)*pz*(x144.value)));
IkReal x141=(x134*x137*x138);
IkReal x142=(pz*x138*x139);
px=0;
py=0;
pp=x134;
sj6=gconst4;
cj6=gconst5;
CheckValue<IkReal> x145 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x145.valid){
continue;
}
j6=((3.14159265)+x140+(((-1.0)*(x145.value))));
CheckValue<IkReal> x146 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x146.valid){
continue;
}
IkReal gconst3=((3.14159265358979)+(((-1.0)*(x146.value)))+x140);
IkReal gconst4=((((0.00714125284441861)*x142))+(((-2999808.50571881)*x141)));
IkReal gconst5=((((-0.999974500928805)*x142))+(((-21422.9372891787)*x141)));
j5eval[0]=pz;
if( IKabs(j5eval[0]) < 0.0000010000000000  )
{
{
IkReal j5eval[1];
IkReal x147=pz*pz;
IkReal x148=IKabs(pz);
IkReal x149=x147;
IkReal x150=x109;
IkReal x156 = x149;
if(IKabs(x156)==0){
continue;
}
IkReal x151=pow(x156,-0.5);
IkReal x152=x111;
if((x149) < -0.00001)
continue;
CheckValue<IkReal> x157=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x149)))),-1);
if(!x157.valid){
continue;
}
if( (((2999885.0)*pz*(x157.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x157.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x153=IKasin(((2999885.0)*pz*(x157.value)));
IkReal x154=(x147*x150*x151);
IkReal x155=(pz*x151*x152);
px=0;
py=0;
pp=x147;
sj6=gconst4;
cj6=gconst5;
CheckValue<IkReal> x158 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x158.valid){
continue;
}
j6=((3.14159265)+x153+(((-1.0)*(x158.value))));
CheckValue<IkReal> x159 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x159.valid){
continue;
}
IkReal gconst3=((3.14159265358979)+(((-1.0)*(x159.value)))+x153);
IkReal gconst4=((((0.00714125284441861)*x155))+(((-2999808.50571881)*x154)));
IkReal gconst5=((((-21422.9372891787)*x154))+(((-0.999974500928805)*x155)));
j5eval[0]=pz;
if( IKabs(j5eval[0]) < 0.0000010000000000  )
{
continue; // no branches [j4, j5]

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
IkReal x160=((0.00200103)*gconst5);
IkReal x161=((0.28019999)*gconst4);
CheckValue<IkReal> x162=IKPowWithIntegerCheck(pz,-1);
if(!x162.valid){
continue;
}
CheckValue<IkReal> x163=IKPowWithIntegerCheck((((pz*x161))+((pz*x160))+(((0.02999885)*pz))),-1);
if(!x163.valid){
continue;
}
if( IKabs(((x162.value)*(((-0.02999885)+(((-1.0)*x161))+(((-1.0)*x160)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((x163.value)*(((0.00710433200289749)+(((0.0785080302749392)*gconst4*gconst5))+(((-0.0005606885859897)*(gconst4*gconst4)))+(((0.00887956168449832)*gconst5))+(((0.0662969736252217)*gconst4))+(((0.0005606885859897)*(gconst5*gconst5))))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr(((x162.value)*(((-0.02999885)+(((-1.0)*x161))+(((-1.0)*x160))))))+IKsqr(((x163.value)*(((0.00710433200289749)+(((0.0785080302749392)*gconst4*gconst5))+(((-0.0005606885859897)*(gconst4*gconst4)))+(((0.00887956168449832)*gconst5))+(((0.0662969736252217)*gconst4))+(((0.0005606885859897)*(gconst5*gconst5)))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j5array[0]=IKatan2(((x162.value)*(((-0.02999885)+(((-1.0)*x161))+(((-1.0)*x160))))), ((x163.value)*(((0.00710433200289749)+(((0.0785080302749392)*gconst4*gconst5))+(((-0.0005606885859897)*(gconst4*gconst4)))+(((0.00887956168449832)*gconst5))+(((0.0662969736252217)*gconst4))+(((0.0005606885859897)*(gconst5*gconst5)))))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x164=IKcos(j5);
IkReal x165=IKsin(j5);
IkReal x166=((0.28019999)*gconst5);
IkReal x167=((0.00200103)*gconst5);
IkReal x168=((0.00200103)*gconst4);
IkReal x169=((0.28019999)*gconst4);
IkReal x170=(pz*x165);
IkReal x171=((0.28019999)*x164);
IkReal x172=(pz*x164);
evalcond[0]=((0.02999885)+x170+x169+x167);
evalcond[1]=((0.236820144868803)+(((-1.0)*x168))+(((-1.0)*x172))+x166);
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x170))+(((0.473640289737606)*x172))+(((-1.0)*(pz*pz))));
evalcond[3]=((((0.236820144868803)*x165))+(((0.02999885)*x164))+((x164*x167))+((x164*x169))+((x165*x166))+(((-1.0)*x165*x168)));
evalcond[4]=((((-0.236820144868803)*x164))+(((0.02999885)*x165))+((x164*x168))+pz+((x165*x167))+((x165*x169))+(((-1.0)*x164*x166)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
CheckValue<IkReal> x174=IKPowWithIntegerCheck(pz,-1);
if(!x174.valid){
continue;
}
IkReal x173=x174.value;
CheckValue<IkReal> x175=IKPowWithIntegerCheck(x173,-2);
if(!x175.valid){
continue;
}
if( IKabs((x173*(((-0.02999885)+(((-0.00200103)*gconst5))+(((-0.28019999)*gconst4)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((6.25e-14)*x173*(((-788182559912.831)+(((-4055641388.02502)*gconst5))+(((33780910000000.0)*(x175.value)))+(((-567902868206.972)*gconst4)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr((x173*(((-0.02999885)+(((-0.00200103)*gconst5))+(((-0.28019999)*gconst4))))))+IKsqr(((6.25e-14)*x173*(((-788182559912.831)+(((-4055641388.02502)*gconst5))+(((33780910000000.0)*(x175.value)))+(((-567902868206.972)*gconst4))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j5array[0]=IKatan2((x173*(((-0.02999885)+(((-0.00200103)*gconst5))+(((-0.28019999)*gconst4))))), ((6.25e-14)*x173*(((-788182559912.831)+(((-4055641388.02502)*gconst5))+(((33780910000000.0)*(x175.value)))+(((-567902868206.972)*gconst4))))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x176=IKcos(j5);
IkReal x177=IKsin(j5);
IkReal x178=((0.28019999)*gconst5);
IkReal x179=((0.00200103)*gconst5);
IkReal x180=((0.00200103)*gconst4);
IkReal x181=((0.28019999)*gconst4);
IkReal x182=(pz*x177);
IkReal x183=((0.28019999)*x176);
IkReal x184=(pz*x176);
evalcond[0]=((0.02999885)+x179+x181+x182);
evalcond[1]=((0.236820144868803)+(((-1.0)*x180))+(((-1.0)*x184))+x178);
evalcond[2]=((0.0215323265000576)+(((0.473640289737606)*x184))+(((-0.0599977)*x182))+(((-1.0)*(pz*pz))));
evalcond[3]=(((x176*x181))+((x176*x179))+(((-1.0)*x177*x180))+(((0.02999885)*x176))+(((0.236820144868803)*x177))+((x177*x178)));
evalcond[4]=(((x177*x181))+((x176*x180))+(((-0.236820144868803)*x176))+(((0.02999885)*x177))+pz+(((-1.0)*x176*x178))+((x177*x179)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
CheckValue<IkReal> x185 = IKatan2WithCheck(IkReal(((-0.02999885)+(((-0.00200103)*gconst5))+(((-0.28019999)*gconst4)))),IkReal(((0.236820144868803)+(((-0.00200103)*gconst4))+(((0.28019999)*gconst5)))),IKFAST_ATAN2_MAGTHRESH);
if(!x185.valid){
continue;
}
CheckValue<IkReal> x186=IKPowWithIntegerCheck(IKsign(pz),-1);
if(!x186.valid){
continue;
}
j5array[0]=((-1.5707963267949)+(x185.value)+(((1.5707963267949)*(x186.value))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x187=IKcos(j5);
IkReal x188=IKsin(j5);
IkReal x189=((0.28019999)*gconst5);
IkReal x190=((0.00200103)*gconst5);
IkReal x191=((0.00200103)*gconst4);
IkReal x192=((0.28019999)*gconst4);
IkReal x193=(pz*x188);
IkReal x194=((0.28019999)*x187);
IkReal x195=(pz*x187);
evalcond[0]=((0.02999885)+x193+x192+x190);
evalcond[1]=((0.236820144868803)+(((-1.0)*x195))+(((-1.0)*x191))+x189);
evalcond[2]=((0.0215323265000576)+(((0.473640289737606)*x195))+(((-0.0599977)*x193))+(((-1.0)*(pz*pz))));
evalcond[3]=((((-1.0)*x188*x191))+((x187*x192))+((x187*x190))+(((0.02999885)*x187))+((x188*x189))+(((0.236820144868803)*x188)));
evalcond[4]=((((-0.236820144868803)*x187))+((x187*x191))+(((0.02999885)*x188))+((x188*x190))+((x188*x192))+(((-1.0)*x187*x189))+pz);
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
evalcond[0]=IKabs(pz);
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j5eval[1];
px=0;
py=0;
pp=0;
pz=0;
j5eval[0]=((1.0)+(((25.0198236860287)*(sj6*sj6)))+(((6.01014583649717)*sj6)));
if( IKabs(j5eval[0]) < 0.0000010000000000  )
{
continue; // no branches [j4, j5]

} else
{
{
IkReal j5array[2], cj5array[2], sj5array[2];
bool j5valid[2]={false};
_nj5 = 2;
CheckValue<IkReal> x197 = IKatan2WithCheck(IkReal(((0.0490028456674111)+(((0.0354636579336078)*sj6)))),IkReal(((0.0279576637074784)+(((0.279961018819544)*sj6)))),IKFAST_ATAN2_MAGTHRESH);
if(!x197.valid){
continue;
}
IkReal x196=x197.value;
j5array[0]=((-1.0)*x196);
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
j5array[1]=((3.14159265358979)+(((-1.0)*x196)));
sj5array[1]=IKsin(j5array[1]);
cj5array[1]=IKcos(j5array[1]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
if( j5array[1] > IKPI )
{
    j5array[1]-=IK2PI;
}
else if( j5array[1] < -IKPI )
{    j5array[1]+=IK2PI;
}
j5valid[1] = true;
for(int ij5 = 0; ij5 < 2; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 2; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[1];
IkReal x198=IKcos(j5);
IkReal x199=IKsin(j5);
evalcond[0]=((((0.279961018819544)*sj6*x198))+(((-0.0490028456674111)*x199))+(((0.0279576637074784)*x198))+(((-0.0354636579336078)*sj6*x199)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
if( 1 )
{
bgotonextstatement=false;
continue; // branch miss [j4, j5]

}
} while(0);
if( bgotonextstatement )
{
}
}
}
}
}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
IkReal x200=((0.00200103)*cj6);
IkReal x201=((0.28019999)*sj6);
CheckValue<IkReal> x202=IKPowWithIntegerCheck(pz,-1);
if(!x202.valid){
continue;
}
CheckValue<IkReal> x203=IKPowWithIntegerCheck((((pz*x200))+((pz*x201))+(((0.02999885)*pz))),-1);
if(!x203.valid){
continue;
}
if( IKabs(((x202.value)*(((-0.02999885)+(((-1.0)*x200))+(((-1.0)*x201)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((x203.value)*(((0.00654364341690779)+(((0.0011213771719794)*(cj6*cj6)))+(((0.0785080302749392)*cj6*sj6))+(((0.0662969736252217)*sj6))+(((0.00887956168449832)*cj6)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr(((x202.value)*(((-0.02999885)+(((-1.0)*x200))+(((-1.0)*x201))))))+IKsqr(((x203.value)*(((0.00654364341690779)+(((0.0011213771719794)*(cj6*cj6)))+(((0.0785080302749392)*cj6*sj6))+(((0.0662969736252217)*sj6))+(((0.00887956168449832)*cj6))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j5array[0]=IKatan2(((x202.value)*(((-0.02999885)+(((-1.0)*x200))+(((-1.0)*x201))))), ((x203.value)*(((0.00654364341690779)+(((0.0011213771719794)*(cj6*cj6)))+(((0.0785080302749392)*cj6*sj6))+(((0.0662969736252217)*sj6))+(((0.00887956168449832)*cj6))))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x204=IKcos(j5);
IkReal x205=IKsin(j5);
IkReal x206=((0.00200103)*sj6);
IkReal x207=((0.28019999)*sj6);
IkReal x208=((0.00200103)*cj6);
IkReal x209=((0.28019999)*cj6);
IkReal x210=(pz*x205);
IkReal x211=(cj6*x204);
IkReal x212=(pz*x204);
evalcond[0]=((0.02999885)+x210+x207+x208);
evalcond[1]=((0.236820144868803)+(((-1.0)*x206))+x209+(((-1.0)*x212)));
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x210))+(((0.473640289737606)*x212))+(((-1.0)*(pz*pz))));
evalcond[3]=((((0.236820144868803)*x205))+((x205*x209))+(((0.02999885)*x204))+((x204*x208))+((x204*x207))+(((-1.0)*x205*x206)));
evalcond[4]=((((-1.0)*x204*x209))+((x205*x208))+((x205*x207))+(((0.02999885)*x205))+((x204*x206))+pz+(((-0.236820144868803)*x204)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
CheckValue<IkReal> x214=IKPowWithIntegerCheck(pz,-1);
if(!x214.valid){
continue;
}
IkReal x213=x214.value;
CheckValue<IkReal> x215=IKPowWithIntegerCheck(x213,-2);
if(!x215.valid){
continue;
}
if( IKabs((x213*(((-0.02999885)+(((-0.00200103)*cj6))+(((-0.28019999)*sj6)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((6.25e-14)*x213*(((-788182559912.831)+(((-567902868206.972)*sj6))+(((-4055641388.02502)*cj6))+(((33780910000000.0)*(x215.value))))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr((x213*(((-0.02999885)+(((-0.00200103)*cj6))+(((-0.28019999)*sj6))))))+IKsqr(((6.25e-14)*x213*(((-788182559912.831)+(((-567902868206.972)*sj6))+(((-4055641388.02502)*cj6))+(((33780910000000.0)*(x215.value)))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j5array[0]=IKatan2((x213*(((-0.02999885)+(((-0.00200103)*cj6))+(((-0.28019999)*sj6))))), ((6.25e-14)*x213*(((-788182559912.831)+(((-567902868206.972)*sj6))+(((-4055641388.02502)*cj6))+(((33780910000000.0)*(x215.value)))))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x216=IKcos(j5);
IkReal x217=IKsin(j5);
IkReal x218=((0.00200103)*sj6);
IkReal x219=((0.28019999)*sj6);
IkReal x220=((0.00200103)*cj6);
IkReal x221=((0.28019999)*cj6);
IkReal x222=(pz*x217);
IkReal x223=(cj6*x216);
IkReal x224=(pz*x216);
evalcond[0]=((0.02999885)+x219+x220+x222);
evalcond[1]=((0.236820144868803)+x221+(((-1.0)*x218))+(((-1.0)*x224)));
evalcond[2]=((0.0215323265000576)+(((0.473640289737606)*x224))+(((-0.0599977)*x222))+(((-1.0)*(pz*pz))));
evalcond[3]=(((x216*x220))+((x216*x219))+(((-1.0)*x217*x218))+((x217*x221))+(((0.236820144868803)*x217))+(((0.02999885)*x216)));
evalcond[4]=((((-1.0)*x216*x221))+((x216*x218))+(((-0.236820144868803)*x216))+pz+((x217*x220))+((x217*x219))+(((0.02999885)*x217)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
CheckValue<IkReal> x225 = IKatan2WithCheck(IkReal(((-0.02999885)+(((-0.00200103)*cj6))+(((-0.28019999)*sj6)))),IkReal(((0.236820144868803)+(((-0.00200103)*sj6))+(((0.28019999)*cj6)))),IKFAST_ATAN2_MAGTHRESH);
if(!x225.valid){
continue;
}
CheckValue<IkReal> x226=IKPowWithIntegerCheck(IKsign(pz),-1);
if(!x226.valid){
continue;
}
j5array[0]=((-1.5707963267949)+(x225.value)+(((1.5707963267949)*(x226.value))));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x227=IKcos(j5);
IkReal x228=IKsin(j5);
IkReal x229=((0.00200103)*sj6);
IkReal x230=((0.28019999)*sj6);
IkReal x231=((0.00200103)*cj6);
IkReal x232=((0.28019999)*cj6);
IkReal x233=(pz*x228);
IkReal x234=(cj6*x227);
IkReal x235=(pz*x227);
evalcond[0]=((0.02999885)+x233+x230+x231);
evalcond[1]=((0.236820144868803)+x232+(((-1.0)*x235))+(((-1.0)*x229)));
evalcond[2]=((0.0215323265000576)+(((-1.0)*(pz*pz)))+(((-0.0599977)*x233))+(((0.473640289737606)*x235)));
evalcond[3]=((((0.02999885)*x227))+((x228*x232))+(((-1.0)*x228*x229))+(((0.236820144868803)*x228))+((x227*x231))+((x227*x230)));
evalcond[4]=(((x227*x229))+(((0.02999885)*x228))+(((-1.0)*x227*x232))+((x228*x231))+((x228*x230))+(((-0.236820144868803)*x227))+pz);
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
if( 1 )
{
bgotonextstatement=false;
continue; // branch miss [j4, j5]

}
} while(0);
if( bgotonextstatement )
{
}
}
}

} else
{
{
IkReal j5array[2], cj5array[2], sj5array[2];
bool j5valid[2]={false};
_nj5 = 2;
IkReal x236=((-0.236820144868803)+(((-0.28019999)*cj6))+(((0.00200103)*sj6)));
IkReal x237=((0.02999885)+(((0.00200103)*cj6))+(((0.28019999)*sj6)));
CheckValue<IkReal> x240 = IKatan2WithCheck(IkReal(x236),IkReal(x237),IKFAST_ATAN2_MAGTHRESH);
if(!x240.valid){
continue;
}
IkReal x238=((1.0)*(x240.value));
if((((x237*x237)+(x236*x236))) < -0.00001)
continue;
CheckValue<IkReal> x241=IKPowWithIntegerCheck(IKabs(IKsqrt(((x237*x237)+(x236*x236)))),-1);
if(!x241.valid){
continue;
}
if( ((pz*(x241.value))) < -1-IKFAST_SINCOS_THRESH || ((pz*(x241.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x239=IKasin((pz*(x241.value)));
j5array[0]=((((-1.0)*x238))+(((-1.0)*x239)));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
j5array[1]=((3.14159265358979)+(((-1.0)*x238))+x239);
sj5array[1]=IKsin(j5array[1]);
cj5array[1]=IKcos(j5array[1]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
if( j5array[1] > IKPI )
{
    j5array[1]-=IK2PI;
}
else if( j5array[1] < -IKPI )
{    j5array[1]+=IK2PI;
}
j5valid[1] = true;
for(int ij5 = 0; ij5 < 2; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 2; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];

{
IkReal j4eval[1];
j4eval[0]=((IKabs(px))+(((0.5)*(IKabs(py)))));
if( IKabs(j4eval[0]) < 0.0000000100000000  )
{
{
IkReal j4eval[1];
j4eval[0]=((IKabs(((14.9917042722998)+cj6+(((499.74263254424)*cj5*px))+(((499.74263254424)*pz*sj5))+(((140.02788064147)*sj6)))))+(((999.485265088479)*(IKabs((cj5*py))))));
if( IKabs(j4eval[0]) < 0.0000000100000000  )
{
{
IkReal j4eval[1];
j4eval[0]=((IKabs(((118.349122636244)+(((-1.0)*sj6))+(((140.02788064147)*cj6))+(((499.74263254424)*px*sj5))+(((-499.74263254424)*cj5*pz)))))+(((999.485265088479)*(IKabs((py*sj5))))));
if( IKabs(j4eval[0]) < 0.0000000100000000  )
{
{
IkReal evalcond[1];
bool bgotonextstatement = true;
do
{
evalcond[0]=((IKabs(px))+(IKabs(py)));
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j4array[1], cj4array[1], sj4array[1];
bool j4valid[1]={false};
_nj4 = 1;
j4array[0]=0;
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
for(int ij4 = 0; ij4 < 1; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 1; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
if( 1 )
{
bgotonextstatement=false;
continue; // branch miss [j4]

}
} while(0);
if( bgotonextstatement )
{
}
}
}

} else
{
IkReal op[2+1], zeror[2];
int numroots;
IkReal x242=((140.02788064147)*cj6);
IkReal x243=((1.0)*sj6);
IkReal x244=((499.74263254424)*px*sj5);
IkReal x245=((499.74263254424)*cj5*pz);
IkReal x246=((118.349122636244)+x242);
IkReal x247=(x243+x245);
op[0]=(x246+x244+(((-1.0)*x247)));
op[1]=((-999.485265088479)*py*sj5);
op[2]=(x246+(((-1.0)*x244))+(((-1.0)*x247)));
polyroots2(op,zeror,numroots);
IkReal j4array[2], cj4array[2], sj4array[2], tempj4array[1];
int numsolutions = 0;
for(int ij4 = 0; ij4 < numroots; ++ij4)
{
IkReal htj4 = zeror[ij4];
tempj4array[0]=((2.0)*(atan(htj4)));
for(int kj4 = 0; kj4 < 1; ++kj4)
{
j4array[numsolutions] = tempj4array[kj4];
if( j4array[numsolutions] > IKPI )
{
    j4array[numsolutions]-=IK2PI;
}
else if( j4array[numsolutions] < -IKPI )
{
    j4array[numsolutions]+=IK2PI;
}
sj4array[numsolutions] = IKsin(j4array[numsolutions]);
cj4array[numsolutions] = IKcos(j4array[numsolutions]);
numsolutions++;
}
}
bool j4valid[2]={true,true};
_nj4 = 2;
for(int ij4 = 0; ij4 < numsolutions; ++ij4)
    {
if( !j4valid[ij4] )
{
    continue;
}
    j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];
htj4 = IKtan(j4/2);

_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < numsolutions; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
    }

}

}

} else
{
IkReal op[2+1], zeror[2];
int numroots;
IkReal x248=((140.02788064147)*sj6);
IkReal x249=((499.74263254424)*pz*sj5);
IkReal x250=((499.74263254424)*cj5*px);
IkReal x251=((14.9917042722998)+cj6+x249+x248);
op[0]=(x250+x251);
op[1]=((-999.485265088479)*cj5*py);
op[2]=(x251+(((-1.0)*x250)));
polyroots2(op,zeror,numroots);
IkReal j4array[2], cj4array[2], sj4array[2], tempj4array[1];
int numsolutions = 0;
for(int ij4 = 0; ij4 < numroots; ++ij4)
{
IkReal htj4 = zeror[ij4];
tempj4array[0]=((2.0)*(atan(htj4)));
for(int kj4 = 0; kj4 < 1; ++kj4)
{
j4array[numsolutions] = tempj4array[kj4];
if( j4array[numsolutions] > IKPI )
{
    j4array[numsolutions]-=IK2PI;
}
else if( j4array[numsolutions] < -IKPI )
{
    j4array[numsolutions]+=IK2PI;
}
sj4array[numsolutions] = IKsin(j4array[numsolutions]);
cj4array[numsolutions] = IKcos(j4array[numsolutions]);
numsolutions++;
}
}
bool j4valid[2]={true,true};
_nj4 = 2;
for(int ij4 = 0; ij4 < numsolutions; ++ij4)
    {
if( !j4valid[ij4] )
{
    continue;
}
    j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];
htj4 = IKtan(j4/2);

_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < numsolutions; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
    }

}

}

} else
{
IkReal op[2+1], zeror[2];
int numroots;
op[0]=py;
op[1]=((2.0)*px);
op[2]=((-1.0)*py);
polyroots2(op,zeror,numroots);
IkReal j4array[2], cj4array[2], sj4array[2], tempj4array[1];
int numsolutions = 0;
for(int ij4 = 0; ij4 < numroots; ++ij4)
{
IkReal htj4 = zeror[ij4];
tempj4array[0]=((2.0)*(atan(htj4)));
for(int kj4 = 0; kj4 < 1; ++kj4)
{
j4array[numsolutions] = tempj4array[kj4];
if( j4array[numsolutions] > IKPI )
{
    j4array[numsolutions]-=IK2PI;
}
else if( j4array[numsolutions] < -IKPI )
{
    j4array[numsolutions]+=IK2PI;
}
sj4array[numsolutions] = IKsin(j4array[numsolutions]);
cj4array[numsolutions] = IKcos(j4array[numsolutions]);
numsolutions++;
}
}
bool j4valid[2]={true,true};
_nj4 = 2;
for(int ij4 = 0; ij4 < numsolutions; ++ij4)
    {
if( !j4valid[ij4] )
{
    continue;
}
    j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];
htj4 = IKtan(j4/2);

_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < numsolutions; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
    }

}

}
}
}

}

}

} else
{
{
IkReal j4array[2], cj4array[2], sj4array[2];
bool j4valid[2]={false};
_nj4 = 2;
CheckValue<IkReal> x253 = IKatan2WithCheck(IkReal(((-1.0)*py)),IkReal(px),IKFAST_ATAN2_MAGTHRESH);
if(!x253.valid){
continue;
}
IkReal x252=x253.value;
j4array[0]=((-1.0)*x252);
sj4array[0]=IKsin(j4array[0]);
cj4array[0]=IKcos(j4array[0]);
j4array[1]=((3.14159265358979)+(((-1.0)*x252)));
sj4array[1]=IKsin(j4array[1]);
cj4array[1]=IKcos(j4array[1]);
if( j4array[0] > IKPI )
{
    j4array[0]-=IK2PI;
}
else if( j4array[0] < -IKPI )
{    j4array[0]+=IK2PI;
}
j4valid[0] = true;
if( j4array[1] > IKPI )
{
    j4array[1]-=IK2PI;
}
else if( j4array[1] < -IKPI )
{    j4array[1]+=IK2PI;
}
j4valid[1] = true;
for(int ij4 = 0; ij4 < 2; ++ij4)
{
if( !j4valid[ij4] )
{
    continue;
}
_ij4[0] = ij4; _ij4[1] = -1;
for(int iij4 = ij4+1; iij4 < 2; ++iij4)
{
if( j4valid[iij4] && IKabs(cj4array[ij4]-cj4array[iij4]) < IKFAST_SOLUTION_THRESH && IKabs(sj4array[ij4]-sj4array[iij4]) < IKFAST_SOLUTION_THRESH )
{
    j4valid[iij4]=false; _ij4[1] = iij4; break; 
}
}
j4 = j4array[ij4]; cj4 = cj4array[ij4]; sj4 = sj4array[ij4];

{
IkReal j5eval[3];
IkReal x254=cj6*cj6;
IkReal x255=(py*sj4);
IkReal x256=((140.02788064147)*sj6);
IkReal x257=((0.28019999)*sj6);
IkReal x258=(cj4*px);
IkReal x259=((0.00200103)*cj6);
IkReal x260=(cj6*pz);
IkReal x261=((1.0)*cj6);
IkReal x262=(pz*sj6);
IkReal x263=(cj6*sj6);
j5eval[0]=((((118.349122636244)*pz))+(((-1.0)*x255*x261))+(((-1.0)*x262))+(((-14.9917042722998)*x258))+(((-14.9917042722998)*x255))+(((140.02788064147)*x260))+(((-1.0)*x258*x261))+(((-1.0)*x255*x256))+(((-1.0)*x256*x258)));
j5eval[1]=((IKabs(((-0.0794119653973226)+(((-0.000120057197631)*cj6))+(((-0.0011213771719794)*x263))+(pz*pz)+(((-0.016811354940023)*sj6))+(((0.0785080302749392)*x254)))))+(IKabs(((-0.00654364341690779)+(((-0.0662969736252217)*sj6))+((pz*x255))+((pz*x258))+(((-0.0011213771719794)*x254))+(((-0.0785080302749392)*x263))+(((-0.00887956168449832)*cj6))))));
j5eval[2]=IKsign(((((-0.00200103)*x262))+(((-0.02999885)*x255))+(((-0.02999885)*x258))+(((-1.0)*x255*x257))+(((-1.0)*x255*x259))+(((-1.0)*x257*x258))+(((0.28019999)*x260))+(((0.236820144868803)*pz))+(((-1.0)*x258*x259))));
if( IKabs(j5eval[0]) < 0.0000010000000000  || IKabs(j5eval[1]) < 0.0000010000000000  || IKabs(j5eval[2]) < 0.0000010000000000  )
{
{
IkReal j5eval[3];
IkReal x264=cj6*cj6;
IkReal x265=(cj4*px);
IkReal x266=((0.28019999)*cj6);
IkReal x267=((0.00200103)*sj6);
IkReal x268=(py*sj4);
IkReal x269=((140.02788064147)*cj6);
IkReal x270=(cj6*sj6);
IkReal x271=((1.0)*pz);
IkReal x272=(pz*sj6);
j5eval[0]=((((-14.9917042722998)*pz))+(((-1.0)*cj6*x271))+(((-1.0)*x268*x269))+((sj6*x265))+((sj6*x268))+(((-140.02788064147)*x272))+(((-1.0)*x265*x269))+(((-118.349122636244)*x265))+(((-118.349122636244)*x268)));
j5eval[1]=((IKabs(((-0.00654364341690779)+(((-0.0662969736252217)*sj6))+(((-0.0011213771719794)*x264))+(((-1.0)*x265*x271))+(((-0.0785080302749392)*x270))+(((-1.0)*x268*x271))+(((-0.00887956168449832)*cj6)))))+(IKabs(((-0.0560877851367418)+(((0.0011213771719794)*x270))+(((-0.132714004448074)*cj6))+(((0.000947768428973642)*sj6))+(pz*pz)+(((-0.0785080302749392)*x264))))));
j5eval[2]=IKsign((((x267*x268))+(((-0.236820144868803)*x265))+(((-0.236820144868803)*x268))+(((-0.00200103)*cj6*pz))+(((-0.02999885)*pz))+(((-1.0)*x265*x266))+(((-1.0)*x266*x268))+((x265*x267))+(((-0.28019999)*x272))));
if( IKabs(j5eval[0]) < 0.0000010000000000  || IKabs(j5eval[1]) < 0.0000010000000000  || IKabs(j5eval[2]) < 0.0000010000000000  )
{
{
IkReal j5eval[2];
j5eval[0]=((-8.54155839473537)+(((-1.0)*sj6))+(((-8.37352017169531)*cj6)));
j5eval[1]=IKsign(((-0.135499750534064)+(((-0.0158635865110494)*sj6))+(((-0.132834061645705)*cj6))));
if( IKabs(j5eval[0]) < 0.0000010000000000  || IKabs(j5eval[1]) < 0.0000010000000000  )
{
continue; // no branches [j5]

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
IkReal x273=(cj6*pz);
IkReal x274=(cj4*px);
IkReal x275=((0.28019999)*sj6);
IkReal x276=(py*sj4);
IkReal x277=((0.00200103)*sj6);
IkReal x278=((0.28019999)*cj6);
IkReal x279=((0.00200103)*x276);
CheckValue<IkReal> x280=IKPowWithIntegerCheck(IKsign(((-0.135499750534064)+(((-0.0158635865110494)*sj6))+(((-0.132834061645705)*cj6)))),-1);
if(!x280.valid){
continue;
}
CheckValue<IkReal> x281 = IKatan2WithCheck(IkReal(((((-0.236820144868803)*x274))+(((-0.236820144868803)*x276))+(((-1.0)*x274*x278))+((x274*x277))+(((0.00200103)*x273))+(((0.02999885)*pz))+((x276*x277))+((pz*x275))+(((-1.0)*x276*x278)))),IkReal(((((-1.0)*x274*x275))+(((-1.0)*cj6*x279))+(((-0.02999885)*x274))+(((-0.02999885)*x276))+(((-0.236820144868803)*pz))+(((-0.00200103)*cj6*x274))+(((-1.0)*x275*x276))+((pz*x277))+(((-0.28019999)*x273)))),IKFAST_ATAN2_MAGTHRESH);
if(!x281.valid){
continue;
}
j5array[0]=((-1.5707963267949)+(((1.5707963267949)*(x280.value)))+(x281.value));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x282=IKcos(j5);
IkReal x283=IKsin(j5);
IkReal x284=((0.00200103)*cj6);
IkReal x285=(cj4*px);
IkReal x286=((0.00200103)*sj6);
IkReal x287=((0.28019999)*cj6);
IkReal x288=(py*sj4);
IkReal x289=((0.0599977)*x282);
IkReal x290=(sj6*x282);
IkReal x291=(pz*x283);
IkReal x292=((0.28019999)*x283);
IkReal x293=(pz*x282);
IkReal x294=((1.0)*x283);
IkReal x295=((1.0)*x282);
IkReal x296=((0.473640289737606)*x283);
evalcond[0]=((0.02999885)+(((-1.0)*x285*x295))+x291+x284+(((-1.0)*x288*x295))+(((0.28019999)*sj6)));
evalcond[1]=((0.236820144868803)+(((-1.0)*x293))+(((-1.0)*x285*x294))+x287+(((-1.0)*x288*x294))+(((-1.0)*x286)));
evalcond[2]=((((-0.236820144868803)*x282))+(((-1.0)*x282*x287))+pz+(((0.02999885)*x283))+((sj6*x292))+((x282*x286))+((x283*x284)));
evalcond[3]=((((0.28019999)*x290))+(((-1.0)*x288))+(((-1.0)*x285))+(((0.02999885)*x282))+(((0.236820144868803)*x283))+((x282*x284))+((x283*x287))+(((-1.0)*x283*x286)));
evalcond[4]=((0.0215323265000576)+(((-1.0)*(px*px)))+((x285*x289))+((x288*x289))+((x285*x296))+(((-0.0599977)*x291))+(((-1.0)*(pz*pz)))+(((-1.0)*(py*py)))+((x288*x296))+(((0.473640289737606)*x293)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
IkReal x297=cj6*cj6;
IkReal x298=(py*sj4);
IkReal x299=((0.00200103)*sj6);
IkReal x300=((1.0)*pz);
IkReal x301=(cj4*px);
IkReal x302=(cj6*sj6);
IkReal x303=((0.28019999)*cj6);
CheckValue<IkReal> x304=IKPowWithIntegerCheck(IKsign(((((-1.0)*x298*x303))+(((-1.0)*x301*x303))+((x299*x301))+(((-0.28019999)*pz*sj6))+((x298*x299))+(((-0.00200103)*cj6*pz))+(((-0.236820144868803)*x298))+(((-0.236820144868803)*x301))+(((-0.02999885)*pz)))),-1);
if(!x304.valid){
continue;
}
CheckValue<IkReal> x305 = IKatan2WithCheck(IkReal(((-0.0560877851367418)+(((0.0011213771719794)*x302))+(((-0.132714004448074)*cj6))+(((0.000947768428973642)*sj6))+(pz*pz)+(((-0.0785080302749392)*x297)))),IkReal(((-0.00654364341690779)+(((-1.0)*x298*x300))+(((-0.0662969736252217)*sj6))+(((-0.0785080302749392)*x302))+(((-0.00887956168449832)*cj6))+(((-1.0)*x300*x301))+(((-0.0011213771719794)*x297)))),IKFAST_ATAN2_MAGTHRESH);
if(!x305.valid){
continue;
}
j5array[0]=((-1.5707963267949)+(((1.5707963267949)*(x304.value)))+(x305.value));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x306=IKcos(j5);
IkReal x307=IKsin(j5);
IkReal x308=((0.00200103)*cj6);
IkReal x309=(cj4*px);
IkReal x310=((0.00200103)*sj6);
IkReal x311=((0.28019999)*cj6);
IkReal x312=(py*sj4);
IkReal x313=((0.0599977)*x306);
IkReal x314=(sj6*x306);
IkReal x315=(pz*x307);
IkReal x316=((0.28019999)*x307);
IkReal x317=(pz*x306);
IkReal x318=((1.0)*x307);
IkReal x319=((1.0)*x306);
IkReal x320=((0.473640289737606)*x307);
evalcond[0]=((0.02999885)+(((-1.0)*x312*x319))+x308+x315+(((-1.0)*x309*x319))+(((0.28019999)*sj6)));
evalcond[1]=((0.236820144868803)+(((-1.0)*x312*x318))+x311+(((-1.0)*x310))+(((-1.0)*x317))+(((-1.0)*x309*x318)));
evalcond[2]=(((sj6*x316))+(((-1.0)*x306*x311))+((x306*x310))+pz+(((-0.236820144868803)*x306))+(((0.02999885)*x307))+((x307*x308)));
evalcond[3]=((((-1.0)*x309))+((x307*x311))+(((0.28019999)*x314))+(((-1.0)*x307*x310))+(((0.02999885)*x306))+(((-1.0)*x312))+(((0.236820144868803)*x307))+((x306*x308)));
evalcond[4]=((0.0215323265000576)+(((-1.0)*(px*px)))+((x312*x313))+(((-0.0599977)*x315))+(((0.473640289737606)*x317))+((x312*x320))+((x309*x313))+(((-1.0)*(pz*pz)))+((x309*x320))+(((-1.0)*(py*py))));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}

} else
{
{
IkReal j5array[1], cj5array[1], sj5array[1];
bool j5valid[1]={false};
_nj5 = 1;
IkReal x321=cj6*cj6;
IkReal x322=(py*sj4);
IkReal x323=(cj4*px);
IkReal x324=((0.28019999)*sj6);
IkReal x325=(cj6*sj6);
IkReal x326=((0.00200103)*cj6);
CheckValue<IkReal> x327=IKPowWithIntegerCheck(IKsign(((((-0.02999885)*x323))+(((-0.02999885)*x322))+(((-1.0)*x322*x324))+(((-1.0)*x322*x326))+(((-1.0)*x323*x326))+(((-1.0)*x323*x324))+(((-0.00200103)*pz*sj6))+(((0.236820144868803)*pz))+(((0.28019999)*cj6*pz)))),-1);
if(!x327.valid){
continue;
}
CheckValue<IkReal> x328 = IKatan2WithCheck(IkReal(((-0.00654364341690779)+(((-0.0011213771719794)*x321))+(((-0.0662969736252217)*sj6))+((pz*x323))+((pz*x322))+(((-0.0785080302749392)*x325))+(((-0.00887956168449832)*cj6)))),IkReal(((-0.0794119653973226)+(((-0.000120057197631)*cj6))+(((-0.0011213771719794)*x325))+(pz*pz)+(((0.0785080302749392)*x321))+(((-0.016811354940023)*sj6)))),IKFAST_ATAN2_MAGTHRESH);
if(!x328.valid){
continue;
}
j5array[0]=((-1.5707963267949)+(((1.5707963267949)*(x327.value)))+(x328.value));
sj5array[0]=IKsin(j5array[0]);
cj5array[0]=IKcos(j5array[0]);
if( j5array[0] > IKPI )
{
    j5array[0]-=IK2PI;
}
else if( j5array[0] < -IKPI )
{    j5array[0]+=IK2PI;
}
j5valid[0] = true;
for(int ij5 = 0; ij5 < 1; ++ij5)
{
if( !j5valid[ij5] )
{
    continue;
}
_ij5[0] = ij5; _ij5[1] = -1;
for(int iij5 = ij5+1; iij5 < 1; ++iij5)
{
if( j5valid[iij5] && IKabs(cj5array[ij5]-cj5array[iij5]) < IKFAST_SOLUTION_THRESH && IKabs(sj5array[ij5]-sj5array[iij5]) < IKFAST_SOLUTION_THRESH )
{
    j5valid[iij5]=false; _ij5[1] = iij5; break; 
}
}
j5 = j5array[ij5]; cj5 = cj5array[ij5]; sj5 = sj5array[ij5];
{
IkReal evalcond[5];
IkReal x329=IKcos(j5);
IkReal x330=IKsin(j5);
IkReal x331=((0.00200103)*cj6);
IkReal x332=(cj4*px);
IkReal x333=((0.00200103)*sj6);
IkReal x334=((0.28019999)*cj6);
IkReal x335=(py*sj4);
IkReal x336=((0.0599977)*x329);
IkReal x337=(sj6*x329);
IkReal x338=(pz*x330);
IkReal x339=((0.28019999)*x330);
IkReal x340=(pz*x329);
IkReal x341=((1.0)*x330);
IkReal x342=((1.0)*x329);
IkReal x343=((0.473640289737606)*x330);
evalcond[0]=((0.02999885)+(((-1.0)*x335*x342))+(((-1.0)*x332*x342))+x338+x331+(((0.28019999)*sj6)));
evalcond[1]=((0.236820144868803)+(((-1.0)*x335*x341))+(((-1.0)*x332*x341))+x334+(((-1.0)*x333))+(((-1.0)*x340)));
evalcond[2]=(((x330*x331))+(((-1.0)*x329*x334))+pz+((x329*x333))+(((0.02999885)*x330))+((sj6*x339))+(((-0.236820144868803)*x329)));
evalcond[3]=(((x330*x334))+(((0.02999885)*x329))+(((0.28019999)*x337))+(((-1.0)*x335))+(((-1.0)*x332))+(((-1.0)*x330*x333))+((x329*x331))+(((0.236820144868803)*x330)));
evalcond[4]=((0.0215323265000576)+((x335*x343))+((x335*x336))+(((-1.0)*(px*px)))+((x332*x336))+((x332*x343))+(((-0.0599977)*x338))+(((0.473640289737606)*x340))+(((-1.0)*(pz*pz)))+(((-1.0)*(py*py))));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j4;
vinfos[0].indices[0] = _ij4[0];
vinfos[0].indices[1] = _ij4[1];
vinfos[0].maxsolutions = _nj4;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j5;
vinfos[1].indices[0] = _ij5[0];
vinfos[1].indices[1] = _ij5[1];
vinfos[1].maxsolutions = _nj5;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j6;
vinfos[2].indices[0] = _ij6[0];
vinfos[2].indices[1] = _ij6[1];
vinfos[2].maxsolutions = _nj6;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}
}
}

}

}
}
}
}
return solutions.GetNumSolutions()>0;
}
static inline void polyroots2(IkReal rawcoeffs[2+1], IkReal rawroots[2], int& numroots) {
    IkReal det = rawcoeffs[1]*rawcoeffs[1]-4*rawcoeffs[0]*rawcoeffs[2];
    if( det < 0 ) {
        numroots=0;
    }
    else if( det == 0 ) {
        rawroots[0] = -0.5*rawcoeffs[1]/rawcoeffs[0];
        numroots = 1;
    }
    else {
        det = IKsqrt(det);
        rawroots[0] = (-rawcoeffs[1]+det)/(2*rawcoeffs[0]);
        rawroots[1] = (-rawcoeffs[1]-det)/(2*rawcoeffs[0]);//rawcoeffs[2]/(rawcoeffs[0]*rawroots[0]);
        numroots = 2;
    }
}
};


/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API bool ComputeIk2(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions, void* pOpenRAVEManip) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API const char* GetKinematicsHash() { return "<robot:GenericRobot - ugv_roarm (1d4761435531415b9ed8c4932e62fc06)>"; }

IKFAST_API const char* GetIkFastVersion() { return "0x1000004b"; }

#ifdef IKFAST_NAMESPACE
} // end namespace
#endif

#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>
#ifdef IKFAST_NAMESPACE
using namespace IKFAST_NAMESPACE;
#endif
int main(int argc, char** argv)
{
    if( argc != 12+GetNumFreeParameters()+1 ) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",GetNumFreeParameters());
        return 1;
    }

    IkSolutionList<IkReal> solutions;
    std::vector<IkReal> vfree(GetNumFreeParameters());
    IkReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    for(std::size_t i = 0; i < vfree.size(); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ComputeIk(eetrans, eerot, vfree.size() > 0 ? &vfree[0] : NULL, solutions);

    if( !bSuccess ) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }

    printf("Found %d ik solutions:\n", (int)solutions.GetNumSolutions());
    std::vector<IkReal> solvalues(GetNumJoints());
    for(std::size_t i = 0; i < solutions.GetNumSolutions(); ++i) {
        const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
        printf("sol%d (free=%d): ", (int)i, (int)sol.GetFree().size());
        std::vector<IkReal> vsolfree(sol.GetFree().size());
        sol.GetSolution(&solvalues[0],vsolfree.size()>0?&vsolfree[0]:NULL);
        for( std::size_t j = 0; j < solvalues.size(); ++j)
            printf("%.15f, ", solvalues[j]);
        printf("\n");
    }
    return 0;
}

#endif
