/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     http://www.apache.org/licenses/LICENSE-2.0
/// 
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 0x1000004b generated on 2025-02-18 17:03:01.972201
/// Generated using solver translation3d
/// To compile with gcc:
///     gcc -lstdc++ ik.cpp
/// To compile without any main function as a shared object (might need -llapack):
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp
#define IKFAST_HAS_LIBRARY
#include "ikfast.h" // found inside share/openrave-X.Y/python/ikfast.h
using namespace ikfast;

// check if the included ikfast version matches what this file was compiled with
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
IKFAST_COMPILE_ASSERT(IKFAST_VERSION==0x1000004b);

#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>

#ifndef IKFAST_ASSERT
#include <stdexcept>
#include <sstream>
#include <iostream>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI  ((IkReal)6.28318530717959)
#define IKPI  ((IkReal)3.14159265358979)
#define IKPI_2  ((IkReal)1.57079632679490)

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#ifndef isinf
#define isinf _isinf
#endif
//#ifndef isfinite
//#define isfinite _isfinite
//#endif
#endif // _MSC_VER

// lapack routines
extern "C" {
  void dgetrf_ (const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
  void zgetrf_ (const int* m, const int* n, std::complex<double>* a, const int* lda, int* ipiv, int* info);
  void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
  void dgesv_ (const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
  void dgetrs_(const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info);
  void dgeev_(const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi,double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info);
}

using namespace std; // necessary to get std math routines

#ifdef IKFAST_NAMESPACE
namespace IKFAST_NAMESPACE {
#endif

inline float IKabs(float f) { return fabsf(f); }
inline double IKabs(double f) { return fabs(f); }

inline float IKsqr(float f) { return f*f; }
inline double IKsqr(double f) { return f*f; }

inline float IKlog(float f) { return logf(f); }
inline double IKlog(double f) { return log(f); }

// allows asin and acos to exceed 1. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_SINCOS_THRESH
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
#endif

// used to check input to atan2 for degenerate cases. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_ATAN2_MAGTHRESH
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
#endif

// minimum distance of separate solutions
#ifndef IKFAST_SOLUTION_THRESH
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#endif

// there are checkpoints in ikfast that are evaluated to make sure they are 0. This threshold speicfies by how much they can deviate
#ifndef IKFAST_EVALCOND_THRESH
#define IKFAST_EVALCOND_THRESH ((IkReal)0.03) // 5D IK has some crazy degenerate cases, but can rely on jacobian refinment to make better, just need good starting point
#endif


inline float IKasin(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(-IKPI_2);
else if( f >= 1 ) return float(IKPI_2);
return asinf(f);
}
inline double IKasin(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asin(f);
}

// return positive value in [0,y)
inline float IKfmod(float x, float y)
{
    while(x < 0) {
        x += y;
    }
    return fmodf(x,y);
}

// return positive value in [0,y)
inline double IKfmod(double x, double y)
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}

inline float IKacos(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(IKPI);
else if( f >= 1 ) return float(0);
return acosf(f);
}
inline double IKacos(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0;
return acos(f);
}
inline float IKsin(float f) { return sinf(f); }
inline double IKsin(double f) { return sin(f); }
inline float IKcos(float f) { return cosf(f); }
inline double IKcos(double f) { return cos(f); }
inline float IKtan(float f) { return tanf(f); }
inline double IKtan(double f) { return tan(f); }
inline float IKsqrt(float f) { if( f <= 0.0f ) return 0.0f; return sqrtf(f); }
inline double IKsqrt(double f) { if( f <= 0.0 ) return 0.0; return sqrt(f); }
inline float IKatan2Simple(float fy, float fx) {
    return atan2f(fy,fx);
}
inline float IKatan2(float fy, float fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return float(IKPI_2);
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2f(fy,fx);
}
inline double IKatan2Simple(double fy, double fx) {
    return atan2(fy,fx);
}
inline double IKatan2(double fy, double fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2(fy,fx);
}

template <typename T>
struct CheckValue
{
    T value;
    bool valid;
};

template <typename T>
inline CheckValue<T> IKatan2WithCheck(T fy, T fx, T epsilon)
{
    CheckValue<T> ret;
    ret.valid = false;
    ret.value = 0;
    if( !isnan(fy) && !isnan(fx) ) {
        if( IKabs(fy) >= IKFAST_ATAN2_MAGTHRESH || IKabs(fx) > IKFAST_ATAN2_MAGTHRESH ) {
            ret.value = IKatan2Simple(fy,fx);
            ret.valid = true;
        }
    }
    return ret;
}

inline float IKsign(float f) {
    if( f > 0 ) {
        return float(1);
    }
    else if( f < 0 ) {
        return float(-1);
    }
    return 0;
}

inline double IKsign(double f) {
    if( f > 0 ) {
        return 1.0;
    }
    else if( f < 0 ) {
        return -1.0;
    }
    return 0;
}

template <typename T>
inline CheckValue<T> IKPowWithIntegerCheck(T f, int n)
{
    CheckValue<T> ret;
    ret.valid = true;
    if( n == 0 ) {
        ret.value = 1.0;
        return ret;
    }
    else if( n == 1 )
    {
        ret.value = f;
        return ret;
    }
    else if( n < 0 )
    {
        if( f == 0 )
        {
            ret.valid = false;
            ret.value = (T)1.0e30;
            return ret;
        }
        if( n == -1 ) {
            ret.value = T(1.0)/f;
            return ret;
        }
    }

    int num = n > 0 ? n : -n;
    if( num == 2 ) {
        ret.value = f*f;
    }
    else if( num == 3 ) {
        ret.value = f*f*f;
    }
    else {
        ret.value = 1.0;
        while(num>0) {
            if( num & 1 ) {
                ret.value *= f;
            }
            num >>= 1;
            f *= f;
        }
    }
    
    if( n < 0 ) {
        ret.value = T(1.0)/ret.value;
    }
    return ret;
}

template <typename T> struct ComplexLess
{
    bool operator()(const complex<T>& lhs, const complex<T>& rhs) const
    {
        if (real(lhs) < real(rhs)) {
            return true;
        }
        if (real(lhs) > real(rhs)) {
            return false;
        }
        return imag(lhs) < imag(rhs);
    }
};

/// solves the forward kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void ComputeFk(const IkReal* j, IkReal* eetrans, IkReal* eerot) {
IkReal x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15;
x0=IKcos(j[0]);
x1=IKcos(j[1]);
x2=IKcos(j[2]);
x3=IKsin(j[1]);
x4=IKsin(j[2]);
x5=IKsin(j[0]);
x6=((0.00200103)*x2);
x7=((0.28019999)*x1);
x8=((0.28019999)*x2);
x9=((0.28019999)*x4);
x10=((0.00200103)*x4);
x11=(x3*x5);
x12=(x1*x5);
x13=(x0*x4);
x14=(x0*x3);
x15=(x0*x1);
eetrans[0]=(((x14*x8))+(((-1.0)*x10*x14))+(((0.236820144868803)*x14))+((x13*x7))+(((0.02999885)*x15))+((x15*x6)));
eetrans[1]=(((x4*x5*x7))+((x11*x8))+(((-1.0)*x10*x11))+((x12*x6))+(((0.236820144868803)*x11))+(((0.02999885)*x12)));
IkReal x16=((1.0)*x3);
eetrans[2]=((0.088)+(((-1.0)*x1*x10))+((x2*x7))+(((-1.0)*x16*x9))+(((-1.0)*x16*x6))+(((-0.02999885)*x3))+(((0.236820144868803)*x1)));
}

IKFAST_API int GetNumFreeParameters() { return 0; }
IKFAST_API int* GetFreeParameters() { return NULL; }
IKFAST_API const int* GetFreeIndices() { return NULL; }
IKFAST_API int GetNumJoints() { return 3; }

IKFAST_API int GetIkRealSize() { return sizeof(IkReal); }

IKFAST_API int GetIkType() { return 0x33000003; }

class IKSolver {
public:
IkReal j0,cj0,sj0,htj0,j0mul,j1,cj1,sj1,htj1,j1mul,j2,cj2,sj2,htj2,j2mul,new_px,px,npx,new_py,py,npy,new_pz,pz,npz,pp;
unsigned char _ij0[2], _nj0,_ij1[2], _nj1,_ij2[2], _nj2;

IkReal j100, cj100, sj100;
unsigned char _ij100[2], _nj100;
bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
j0=numeric_limits<IkReal>::quiet_NaN(); _ij0[0] = -1; _ij0[1] = -1; _nj0 = -1; j1=numeric_limits<IkReal>::quiet_NaN(); _ij1[0] = -1; _ij1[1] = -1; _nj1 = -1; j2=numeric_limits<IkReal>::quiet_NaN(); _ij2[0] = -1; _ij2[1] = -1; _nj2 = -1; 
for(int dummyiter = 0; dummyiter < 1; ++dummyiter) {
    solutions.Clear();
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];

new_px=px;
new_py=py;
new_pz=((-0.088)+pz);
px = new_px; py = new_py; pz = new_pz;
pp=((px*px)+(py*py)+(pz*pz));
{
IkReal j2array[2], cj2array[2], sj2array[2];
bool j2valid[2]={false};
_nj2 = 2;
if( (((-1.0128705456968)+(((7.47507314002149)*(pz*pz)))+(((7.47507314002149)*(px*px)))+(((7.47507314002149)*(py*py))))) < -1-IKFAST_SINCOS_THRESH || (((-1.0128705456968)+(((7.47507314002149)*(pz*pz)))+(((7.47507314002149)*(px*px)))+(((7.47507314002149)*(py*py))))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x17=IKasin(((-1.0128705456968)+(((7.47507314002149)*(pz*pz)))+(((7.47507314002149)*(px*px)))+(((7.47507314002149)*(py*py)))));
j2array[0]=((-1.45193517715052)+(((1.0)*x17)));
sj2array[0]=IKsin(j2array[0]);
cj2array[0]=IKcos(j2array[0]);
j2array[1]=((1.68965747643928)+(((-1.0)*x17)));
sj2array[1]=IKsin(j2array[1]);
cj2array[1]=IKcos(j2array[1]);
if( j2array[0] > IKPI )
{
    j2array[0]-=IK2PI;
}
else if( j2array[0] < -IKPI )
{    j2array[0]+=IK2PI;
}
j2valid[0] = true;
if( j2array[1] > IKPI )
{
    j2array[1]-=IK2PI;
}
else if( j2array[1] < -IKPI )
{    j2array[1]+=IK2PI;
}
j2valid[1] = true;
for(int ij2 = 0; ij2 < 2; ++ij2)
{
if( !j2valid[ij2] )
{
    continue;
}
_ij2[0] = ij2; _ij2[1] = -1;
for(int iij2 = ij2+1; iij2 < 2; ++iij2)
{
if( j2valid[iij2] && IKabs(cj2array[ij2]-cj2array[iij2]) < IKFAST_SOLUTION_THRESH && IKabs(sj2array[ij2]-sj2array[iij2]) < IKFAST_SOLUTION_THRESH )
{
    j2valid[iij2]=false; _ij2[1] = iij2; break; 
}
}
j2 = j2array[ij2]; cj2 = cj2array[ij2]; sj2 = sj2array[ij2];

{
IkReal j0eval[1];
j0eval[0]=((IKabs(px))+(IKabs(py)));
if( IKabs(j0eval[0]) < 0.0000010000000000  )
{
{
IkReal j1eval[1];
j1eval[0]=((3.59210774797445)+sj2+(((4.94945064676092)*(cj2*cj2)))+(((4.94945064676092)*(sj2*sj2)))+(((8.37352017169531)*cj2)));
if( IKabs(j1eval[0]) < 0.0000010000000000  )
{
{
IkReal evalcond[1];
bool bgotonextstatement = true;
do
{
evalcond[0]=((IKabs(px))+(IKabs(py)));
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j1eval[3];
px=0;
py=0;
pp=pz*pz;
j1eval[0]=pz;
j1eval[1]=IKsign(pz);
j1eval[2]=((3.59210774797445)+sj2+(((4.94945064676092)*(cj2*cj2)))+(((4.94945064676092)*(sj2*sj2)))+(((8.37352017169531)*cj2)));
if( IKabs(j1eval[0]) < 0.0000010000000000  || IKabs(j1eval[1]) < 0.0000010000000000  || IKabs(j1eval[2]) < 0.0000010000000000  )
{
{
IkReal j1eval[1];
px=0;
py=0;
pp=pz*pz;
j1eval[0]=pz;
if( IKabs(j1eval[0]) < 0.0000010000000000  )
{
{
IkReal j1eval[2];
px=0;
py=0;
pp=pz*pz;
j1eval[0]=pz;
j1eval[1]=(((cj2*pz))+(((14.9917042722998)*pz))+(((140.02788064147)*pz*sj2)));
if( IKabs(j1eval[0]) < 0.0000010000000000  || IKabs(j1eval[1]) < 0.0000010000000000  )
{
{
IkReal evalcond[1];
bool bgotonextstatement = true;
do
{
IkReal x18=pz*pz;
IkReal x19=IKabs(pz);
IkReal x20=x18;
CheckValue<IkReal> x26=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*x19)),-1);
if(!x26.valid){
continue;
}
IkReal x21=x26.value;
IkReal x27 = x20;
if(IKabs(x27)==0){
continue;
}
IkReal x22=pow(x27,-0.5);
CheckValue<IkReal> x28=IKPowWithIntegerCheck(x19,-2);
if(!x28.valid){
continue;
}
if((((1.0)+(((-0.0114617474126251)*x18*(x28.value))))) < -0.00001)
continue;
IkReal x23=IKsqrt(((1.0)+(((-0.0114617474126251)*x18*(x28.value)))));
IkReal x24=(x18*x21*x22);
IkReal x25=(pz*x22*x23);
if((x20) < -0.00001)
continue;
CheckValue<IkReal> x29=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x20)))),-1);
if(!x29.valid){
continue;
}
if( (((2999885.0)*pz*(x29.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x29.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
CheckValue<IkReal> x30 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x30.valid){
continue;
}
IkReal gconst0=((((-1.0)*(IKasin(((2999885.0)*pz*(x29.value))))))+(((-1.0)*(x30.value))));
IkReal gconst1=((((-2999808.50571881)*x24))+(((-0.00714125284441861)*x25)));
IkReal gconst2=((((-21422.9372891787)*x24))+(((0.999974500928805)*x25)));
CheckValue<IkReal> x31 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x31.valid){
continue;
}
if((pz*pz) < -0.00001)
continue;
CheckValue<IkReal> x32=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(pz*pz)))),-1);
if(!x32.valid){
continue;
}
if( (((2999885.0)*pz*(x32.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x32.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
evalcond[0]=((-3.14159265358979)+(IKfmod(((3.14159265358979)+(IKabs(((x31.value)+(IKasin(((2999885.0)*pz*(x32.value))))+j2)))), 6.28318530717959)));
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j1eval[2];
IkReal x33=pz*pz;
IkReal x34=IKabs(pz);
IkReal x35=x33;
IkReal x36=x21;
IkReal x42 = x35;
if(IKabs(x42)==0){
continue;
}
IkReal x37=pow(x42,-0.5);
IkReal x38=x23;
if((x35) < -0.00001)
continue;
CheckValue<IkReal> x43=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x35)))),-1);
if(!x43.valid){
continue;
}
if( (((2999885.0)*pz*(x43.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x43.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x39=((1.0)*(IKasin(((2999885.0)*pz*(x43.value)))));
IkReal x40=(x33*x36*x37);
IkReal x41=(pz*x37*x38);
px=0;
py=0;
pp=x33;
sj2=gconst1;
cj2=gconst2;
CheckValue<IkReal> x44 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x44.valid){
continue;
}
j2=((((-1.0)*x39))+(((-1.0)*(x44.value))));
CheckValue<IkReal> x45 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x45.valid){
continue;
}
IkReal gconst0=((((-1.0)*(x45.value)))+(((-1.0)*x39)));
IkReal gconst1=((((-2999808.50571881)*x40))+(((-0.00714125284441861)*x41)));
IkReal gconst2=((((0.999974500928805)*x41))+(((-21422.9372891787)*x40)));
j1eval[0]=pz;
j1eval[1]=IKsign(pz);
if( IKabs(j1eval[0]) < 0.0000010000000000  || IKabs(j1eval[1]) < 0.0000010000000000  )
{
{
IkReal j1eval[1];
IkReal x46=pz*pz;
IkReal x47=IKabs(pz);
IkReal x48=x46;
IkReal x49=x21;
IkReal x55 = x48;
if(IKabs(x55)==0){
continue;
}
IkReal x50=pow(x55,-0.5);
IkReal x51=x23;
if((x48) < -0.00001)
continue;
CheckValue<IkReal> x56=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x48)))),-1);
if(!x56.valid){
continue;
}
if( (((2999885.0)*pz*(x56.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x56.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x52=((1.0)*(IKasin(((2999885.0)*pz*(x56.value)))));
IkReal x53=(x46*x49*x50);
IkReal x54=(pz*x50*x51);
px=0;
py=0;
pp=x46;
sj2=gconst1;
cj2=gconst2;
CheckValue<IkReal> x57 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x57.valid){
continue;
}
j2=((((-1.0)*(x57.value)))+(((-1.0)*x52)));
CheckValue<IkReal> x58 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x58.valid){
continue;
}
IkReal gconst0=((((-1.0)*(x58.value)))+(((-1.0)*x52)));
IkReal gconst1=((((-2999808.50571881)*x53))+(((-0.00714125284441861)*x54)));
IkReal gconst2=((((-21422.9372891787)*x53))+(((0.999974500928805)*x54)));
j1eval[0]=pz;
if( IKabs(j1eval[0]) < 0.0000010000000000  )
{
{
IkReal j1eval[1];
IkReal x59=pz*pz;
IkReal x60=IKabs(pz);
IkReal x61=x59;
IkReal x62=x21;
IkReal x68 = x61;
if(IKabs(x68)==0){
continue;
}
IkReal x63=pow(x68,-0.5);
IkReal x64=x23;
if((x61) < -0.00001)
continue;
CheckValue<IkReal> x69=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x61)))),-1);
if(!x69.valid){
continue;
}
if( (((2999885.0)*pz*(x69.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x69.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x65=((1.0)*(IKasin(((2999885.0)*pz*(x69.value)))));
IkReal x66=(x59*x62*x63);
IkReal x67=(pz*x63*x64);
px=0;
py=0;
pp=x59;
sj2=gconst1;
cj2=gconst2;
CheckValue<IkReal> x70 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x70.valid){
continue;
}
j2=((((-1.0)*(x70.value)))+(((-1.0)*x65)));
CheckValue<IkReal> x71 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x71.valid){
continue;
}
IkReal gconst0=((((-1.0)*(x71.value)))+(((-1.0)*x65)));
IkReal gconst1=((((-2999808.50571881)*x66))+(((-0.00714125284441861)*x67)));
IkReal gconst2=((((0.999974500928805)*x67))+(((-21422.9372891787)*x66)));
j1eval[0]=pz;
if( IKabs(j1eval[0]) < 0.0000010000000000  )
{
continue; // no branches [j0, j1]

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
CheckValue<IkReal> x72=IKPowWithIntegerCheck(pz,-1);
if(!x72.valid){
continue;
}
CheckValue<IkReal> x73=IKPowWithIntegerCheck(((((-0.28019999)*gconst2*pz))+(((0.00200103)*gconst1*pz))+(((-0.236820144868803)*pz))),-1);
if(!x73.valid){
continue;
}
if( IKabs(((x72.value)*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((x73.value)*(((0.0008999310013225)+(((0.0785120343960001)*(gconst1*gconst1)))+(((-1.0)*(pz*pz)))+(((0.000120057197631)*gconst2))+(((0.0011213771719794)*gconst1*gconst2))+(((4.0041210609e-6)*(gconst2*gconst2)))+(((0.016811354940023)*gconst1)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr(((x72.value)*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1))))))+IKsqr(((x73.value)*(((0.0008999310013225)+(((0.0785120343960001)*(gconst1*gconst1)))+(((-1.0)*(pz*pz)))+(((0.000120057197631)*gconst2))+(((0.0011213771719794)*gconst1*gconst2))+(((4.0041210609e-6)*(gconst2*gconst2)))+(((0.016811354940023)*gconst1))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j1array[0]=IKatan2(((x72.value)*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1))))), ((x73.value)*(((0.0008999310013225)+(((0.0785120343960001)*(gconst1*gconst1)))+(((-1.0)*(pz*pz)))+(((0.000120057197631)*gconst2))+(((0.0011213771719794)*gconst1*gconst2))+(((4.0041210609e-6)*(gconst2*gconst2)))+(((0.016811354940023)*gconst1))))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x74=IKcos(j1);
IkReal x75=IKsin(j1);
IkReal x76=((0.00200103)*gconst2);
IkReal x77=((0.28019999)*gconst2);
IkReal x78=((0.00200103)*gconst1);
IkReal x79=((0.28019999)*gconst1);
IkReal x80=(pz*x75);
IkReal x81=(pz*x74);
evalcond[0]=((0.02999885)+x76+x79+x80);
evalcond[1]=((0.236820144868803)+(((-1.0)*x78))+x77+(((-1.0)*x81)));
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x80))+(((0.473640289737606)*x81))+(((-1.0)*(pz*pz))));
evalcond[3]=((((0.236820144868803)*x75))+((x75*x77))+(((0.02999885)*x74))+((x74*x76))+((x74*x79))+(((-1.0)*x75*x78)));
evalcond[4]=(((x75*x76))+((x75*x79))+(((-1.0)*x74*x77))+pz+(((-0.236820144868803)*x74))+(((0.02999885)*x75))+((x74*x78)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
CheckValue<IkReal> x83=IKPowWithIntegerCheck(pz,-1);
if(!x83.valid){
continue;
}
IkReal x82=x83.value;
CheckValue<IkReal> x84=IKPowWithIntegerCheck(x82,-2);
if(!x84.valid){
continue;
}
if( IKabs((x82*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((6.25e-14)*x82*(((-788182559912.831)+(((-4055641388.02502)*gconst2))+(((33780910000000.0)*(x84.value)))+(((-567902868206.972)*gconst1)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr((x82*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1))))))+IKsqr(((6.25e-14)*x82*(((-788182559912.831)+(((-4055641388.02502)*gconst2))+(((33780910000000.0)*(x84.value)))+(((-567902868206.972)*gconst1))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j1array[0]=IKatan2((x82*(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1))))), ((6.25e-14)*x82*(((-788182559912.831)+(((-4055641388.02502)*gconst2))+(((33780910000000.0)*(x84.value)))+(((-567902868206.972)*gconst1))))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x85=IKcos(j1);
IkReal x86=IKsin(j1);
IkReal x87=((0.00200103)*gconst2);
IkReal x88=((0.28019999)*gconst2);
IkReal x89=((0.00200103)*gconst1);
IkReal x90=((0.28019999)*gconst1);
IkReal x91=(pz*x86);
IkReal x92=(pz*x85);
evalcond[0]=((0.02999885)+x87+x91+x90);
evalcond[1]=((0.236820144868803)+x88+(((-1.0)*x92))+(((-1.0)*x89)));
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x91))+(((0.473640289737606)*x92))+(((-1.0)*(pz*pz))));
evalcond[3]=((((0.236820144868803)*x86))+((x85*x87))+((x86*x88))+((x85*x90))+(((-1.0)*x86*x89))+(((0.02999885)*x85)));
evalcond[4]=(((x86*x90))+((x85*x89))+((x86*x87))+(((0.02999885)*x86))+pz+(((-1.0)*x85*x88))+(((-0.236820144868803)*x85)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
CheckValue<IkReal> x93 = IKatan2WithCheck(IkReal(((-0.02999885)+(((-0.00200103)*gconst2))+(((-0.28019999)*gconst1)))),IkReal(((0.236820144868803)+(((-0.00200103)*gconst1))+(((0.28019999)*gconst2)))),IKFAST_ATAN2_MAGTHRESH);
if(!x93.valid){
continue;
}
CheckValue<IkReal> x94=IKPowWithIntegerCheck(IKsign(pz),-1);
if(!x94.valid){
continue;
}
j1array[0]=((-1.5707963267949)+(x93.value)+(((1.5707963267949)*(x94.value))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x95=IKcos(j1);
IkReal x96=IKsin(j1);
IkReal x97=((0.00200103)*gconst2);
IkReal x98=((0.28019999)*gconst2);
IkReal x99=((0.00200103)*gconst1);
IkReal x100=((0.28019999)*gconst1);
IkReal x101=(pz*x96);
IkReal x102=(pz*x95);
evalcond[0]=((0.02999885)+x100+x101+x97);
evalcond[1]=((0.236820144868803)+x98+(((-1.0)*x99))+(((-1.0)*x102)));
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x101))+(((-1.0)*(pz*pz)))+(((0.473640289737606)*x102)));
evalcond[3]=(((x96*x98))+((x100*x95))+(((0.236820144868803)*x96))+(((0.02999885)*x95))+((x95*x97))+(((-1.0)*x96*x99)));
evalcond[4]=((((-1.0)*x95*x98))+((x96*x97))+((x100*x96))+(((0.02999885)*x96))+pz+((x95*x99))+(((-0.236820144868803)*x95)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
IkReal x103=pz*pz;
IkReal x104=IKabs(pz);
IkReal x105=x103;
CheckValue<IkReal> x111=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*x104)),-1);
if(!x111.valid){
continue;
}
IkReal x106=x111.value;
IkReal x112 = x105;
if(IKabs(x112)==0){
continue;
}
IkReal x107=pow(x112,-0.5);
CheckValue<IkReal> x113=IKPowWithIntegerCheck(x104,-2);
if(!x113.valid){
continue;
}
if((((1.0)+(((-0.0114617474126251)*x103*(x113.value))))) < -0.00001)
continue;
IkReal x108=IKsqrt(((1.0)+(((-0.0114617474126251)*x103*(x113.value)))));
IkReal x109=(x103*x106*x107);
IkReal x110=(pz*x107*x108);
CheckValue<IkReal> x114 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x114.valid){
continue;
}
if((x105) < -0.00001)
continue;
CheckValue<IkReal> x115=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x105)))),-1);
if(!x115.valid){
continue;
}
if( (((2999885.0)*pz*(x115.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x115.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal gconst3=((3.14159265358979)+(((-1.0)*(x114.value)))+(IKasin(((2999885.0)*pz*(x115.value)))));
IkReal gconst4=((((0.00714125284441861)*x110))+(((-2999808.50571881)*x109)));
IkReal gconst5=((((-21422.9372891787)*x109))+(((-0.999974500928805)*x110)));
CheckValue<IkReal> x116 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x116.valid){
continue;
}
if((pz*pz) < -0.00001)
continue;
CheckValue<IkReal> x117=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(pz*pz)))),-1);
if(!x117.valid){
continue;
}
if( (((2999885.0)*pz*(x117.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x117.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
evalcond[0]=((-3.14159265358979)+(IKfmod(((3.14159265358979)+(IKabs(((-3.14159265358979)+(x116.value)+(((-1.0)*(IKasin(((2999885.0)*pz*(x117.value))))))+j2)))), 6.28318530717959)));
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j1eval[2];
IkReal x118=pz*pz;
IkReal x119=IKabs(pz);
IkReal x120=x118;
IkReal x121=x106;
IkReal x127 = x120;
if(IKabs(x127)==0){
continue;
}
IkReal x122=pow(x127,-0.5);
IkReal x123=x108;
if((x120) < -0.00001)
continue;
CheckValue<IkReal> x128=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x120)))),-1);
if(!x128.valid){
continue;
}
if( (((2999885.0)*pz*(x128.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x128.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x124=IKasin(((2999885.0)*pz*(x128.value)));
IkReal x125=(x118*x121*x122);
IkReal x126=(pz*x122*x123);
px=0;
py=0;
pp=x118;
sj2=gconst4;
cj2=gconst5;
CheckValue<IkReal> x129 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x129.valid){
continue;
}
j2=((3.14159265)+x124+(((-1.0)*(x129.value))));
CheckValue<IkReal> x130 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x130.valid){
continue;
}
IkReal gconst3=((3.14159265358979)+(((-1.0)*(x130.value)))+x124);
IkReal gconst4=((((-2999808.50571881)*x125))+(((0.00714125284441861)*x126)));
IkReal gconst5=((((-21422.9372891787)*x125))+(((-0.999974500928805)*x126)));
j1eval[0]=pz;
j1eval[1]=IKsign(pz);
if( IKabs(j1eval[0]) < 0.0000010000000000  || IKabs(j1eval[1]) < 0.0000010000000000  )
{
{
IkReal j1eval[1];
IkReal x131=pz*pz;
IkReal x132=IKabs(pz);
IkReal x133=x131;
IkReal x134=x106;
IkReal x140 = x133;
if(IKabs(x140)==0){
continue;
}
IkReal x135=pow(x140,-0.5);
IkReal x136=x108;
if((x133) < -0.00001)
continue;
CheckValue<IkReal> x141=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x133)))),-1);
if(!x141.valid){
continue;
}
if( (((2999885.0)*pz*(x141.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x141.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x137=IKasin(((2999885.0)*pz*(x141.value)));
IkReal x138=(x131*x134*x135);
IkReal x139=(pz*x135*x136);
px=0;
py=0;
pp=x131;
sj2=gconst4;
cj2=gconst5;
CheckValue<IkReal> x142 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x142.valid){
continue;
}
j2=((3.14159265)+x137+(((-1.0)*(x142.value))));
CheckValue<IkReal> x143 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x143.valid){
continue;
}
IkReal gconst3=((3.14159265358979)+(((-1.0)*(x143.value)))+x137);
IkReal gconst4=((((-2999808.50571881)*x138))+(((0.00714125284441861)*x139)));
IkReal gconst5=((((-21422.9372891787)*x138))+(((-0.999974500928805)*x139)));
j1eval[0]=pz;
if( IKabs(j1eval[0]) < 0.0000010000000000  )
{
{
IkReal j1eval[1];
IkReal x144=pz*pz;
IkReal x145=IKabs(pz);
IkReal x146=x144;
IkReal x147=x106;
IkReal x153 = x146;
if(IKabs(x153)==0){
continue;
}
IkReal x148=pow(x153,-0.5);
IkReal x149=x108;
if((x146) < -0.00001)
continue;
CheckValue<IkReal> x154=IKPowWithIntegerCheck(IKabs(((28020713.5021685)*(IKsqrt(x146)))),-1);
if(!x154.valid){
continue;
}
if( (((2999885.0)*pz*(x154.value))) < -1-IKFAST_SINCOS_THRESH || (((2999885.0)*pz*(x154.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x150=IKasin(((2999885.0)*pz*(x154.value)));
IkReal x151=(x144*x147*x148);
IkReal x152=(pz*x148*x149);
px=0;
py=0;
pp=x144;
sj2=gconst4;
cj2=gconst5;
CheckValue<IkReal> x155 = IKatan2WithCheck(IkReal(pz),IkReal(((140.027977589922)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x155.valid){
continue;
}
j2=((3.14159265)+x150+(((-1.0)*(x155.value))));
CheckValue<IkReal> x156 = IKatan2WithCheck(IkReal(pz),IkReal(((140.02788064147)*pz)),IKFAST_ATAN2_MAGTHRESH);
if(!x156.valid){
continue;
}
IkReal gconst3=((3.14159265358979)+(((-1.0)*(x156.value)))+x150);
IkReal gconst4=((((0.00714125284441861)*x152))+(((-2999808.50571881)*x151)));
IkReal gconst5=((((-21422.9372891787)*x151))+(((-0.999974500928805)*x152)));
j1eval[0]=pz;
if( IKabs(j1eval[0]) < 0.0000010000000000  )
{
continue; // no branches [j0, j1]

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
IkReal x157=((0.00200103)*gconst5);
IkReal x158=((0.28019999)*gconst4);
CheckValue<IkReal> x159=IKPowWithIntegerCheck(pz,-1);
if(!x159.valid){
continue;
}
CheckValue<IkReal> x160=IKPowWithIntegerCheck(((((0.02999885)*pz))+((pz*x157))+((pz*x158))),-1);
if(!x160.valid){
continue;
}
if( IKabs(((x159.value)*(((-0.02999885)+(((-1.0)*x157))+(((-1.0)*x158)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((x160.value)*(((0.00710433200289749)+(((0.0785080302749392)*gconst4*gconst5))+(((-0.0005606885859897)*(gconst4*gconst4)))+(((0.00887956168449832)*gconst5))+(((0.0662969736252217)*gconst4))+(((0.0005606885859897)*(gconst5*gconst5))))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr(((x159.value)*(((-0.02999885)+(((-1.0)*x157))+(((-1.0)*x158))))))+IKsqr(((x160.value)*(((0.00710433200289749)+(((0.0785080302749392)*gconst4*gconst5))+(((-0.0005606885859897)*(gconst4*gconst4)))+(((0.00887956168449832)*gconst5))+(((0.0662969736252217)*gconst4))+(((0.0005606885859897)*(gconst5*gconst5)))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j1array[0]=IKatan2(((x159.value)*(((-0.02999885)+(((-1.0)*x157))+(((-1.0)*x158))))), ((x160.value)*(((0.00710433200289749)+(((0.0785080302749392)*gconst4*gconst5))+(((-0.0005606885859897)*(gconst4*gconst4)))+(((0.00887956168449832)*gconst5))+(((0.0662969736252217)*gconst4))+(((0.0005606885859897)*(gconst5*gconst5)))))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x161=IKcos(j1);
IkReal x162=IKsin(j1);
IkReal x163=((0.28019999)*gconst5);
IkReal x164=((0.00200103)*gconst5);
IkReal x165=((0.00200103)*gconst4);
IkReal x166=((0.28019999)*gconst4);
IkReal x167=(gconst4*x161);
IkReal x168=(pz*x162);
IkReal x169=(pz*x161);
evalcond[0]=((0.02999885)+x168+x166+x164);
evalcond[1]=((0.236820144868803)+(((-1.0)*x165))+x163+(((-1.0)*x169)));
evalcond[2]=((0.0215323265000576)+(((0.473640289737606)*x169))+(((-0.0599977)*x168))+(((-1.0)*(pz*pz))));
evalcond[3]=((((0.236820144868803)*x162))+((x161*x164))+((x161*x166))+((x162*x163))+(((0.02999885)*x161))+(((-1.0)*x162*x165)));
evalcond[4]=(((x161*x165))+(((-0.236820144868803)*x161))+((x162*x164))+((x162*x166))+(((-1.0)*x161*x163))+(((0.02999885)*x162))+pz);
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
CheckValue<IkReal> x171=IKPowWithIntegerCheck(pz,-1);
if(!x171.valid){
continue;
}
IkReal x170=x171.value;
CheckValue<IkReal> x172=IKPowWithIntegerCheck(x170,-2);
if(!x172.valid){
continue;
}
if( IKabs((x170*(((-0.02999885)+(((-0.00200103)*gconst5))+(((-0.28019999)*gconst4)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((6.25e-14)*x170*(((-788182559912.831)+(((-4055641388.02502)*gconst5))+(((33780910000000.0)*(x172.value)))+(((-567902868206.972)*gconst4)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr((x170*(((-0.02999885)+(((-0.00200103)*gconst5))+(((-0.28019999)*gconst4))))))+IKsqr(((6.25e-14)*x170*(((-788182559912.831)+(((-4055641388.02502)*gconst5))+(((33780910000000.0)*(x172.value)))+(((-567902868206.972)*gconst4))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j1array[0]=IKatan2((x170*(((-0.02999885)+(((-0.00200103)*gconst5))+(((-0.28019999)*gconst4))))), ((6.25e-14)*x170*(((-788182559912.831)+(((-4055641388.02502)*gconst5))+(((33780910000000.0)*(x172.value)))+(((-567902868206.972)*gconst4))))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x173=IKcos(j1);
IkReal x174=IKsin(j1);
IkReal x175=((0.28019999)*gconst5);
IkReal x176=((0.00200103)*gconst5);
IkReal x177=((0.00200103)*gconst4);
IkReal x178=((0.28019999)*gconst4);
IkReal x179=(gconst4*x173);
IkReal x180=(pz*x174);
IkReal x181=(pz*x173);
evalcond[0]=((0.02999885)+x178+x176+x180);
evalcond[1]=((0.236820144868803)+(((-1.0)*x177))+(((-1.0)*x181))+x175);
evalcond[2]=((0.0215323265000576)+(((0.473640289737606)*x181))+(((-0.0599977)*x180))+(((-1.0)*(pz*pz))));
evalcond[3]=((((-1.0)*x174*x177))+((x173*x176))+((x173*x178))+((x174*x175))+(((0.02999885)*x173))+(((0.236820144868803)*x174)));
evalcond[4]=((((-0.236820144868803)*x173))+((x173*x177))+((x174*x176))+((x174*x178))+(((0.02999885)*x174))+pz+(((-1.0)*x173*x175)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
CheckValue<IkReal> x182 = IKatan2WithCheck(IkReal(((-0.02999885)+(((-0.00200103)*gconst5))+(((-0.28019999)*gconst4)))),IkReal(((0.236820144868803)+(((-0.00200103)*gconst4))+(((0.28019999)*gconst5)))),IKFAST_ATAN2_MAGTHRESH);
if(!x182.valid){
continue;
}
CheckValue<IkReal> x183=IKPowWithIntegerCheck(IKsign(pz),-1);
if(!x183.valid){
continue;
}
j1array[0]=((-1.5707963267949)+(x182.value)+(((1.5707963267949)*(x183.value))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x184=IKcos(j1);
IkReal x185=IKsin(j1);
IkReal x186=((0.28019999)*gconst5);
IkReal x187=((0.00200103)*gconst5);
IkReal x188=((0.00200103)*gconst4);
IkReal x189=((0.28019999)*gconst4);
IkReal x190=(gconst4*x184);
IkReal x191=(pz*x185);
IkReal x192=(pz*x184);
evalcond[0]=((0.02999885)+x191+x187+x189);
evalcond[1]=((0.236820144868803)+(((-1.0)*x188))+(((-1.0)*x192))+x186);
evalcond[2]=((0.0215323265000576)+(((0.473640289737606)*x192))+(((-0.0599977)*x191))+(((-1.0)*(pz*pz))));
evalcond[3]=((((0.02999885)*x184))+((x185*x186))+((x184*x187))+((x184*x189))+(((-1.0)*x185*x188))+(((0.236820144868803)*x185)));
evalcond[4]=((((-0.236820144868803)*x184))+(((0.02999885)*x185))+((x185*x187))+((x185*x189))+((x184*x188))+(((-1.0)*x184*x186))+pz);
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
evalcond[0]=IKabs(pz);
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j1eval[1];
px=0;
py=0;
pp=0;
pz=0;
j1eval[0]=((1.0)+(((6.01014583649717)*sj2))+(((25.0198236860287)*(sj2*sj2))));
if( IKabs(j1eval[0]) < 0.0000010000000000  )
{
continue; // no branches [j0, j1]

} else
{
{
IkReal j1array[2], cj1array[2], sj1array[2];
bool j1valid[2]={false};
_nj1 = 2;
CheckValue<IkReal> x194 = IKatan2WithCheck(IkReal(((0.0490028456674111)+(((0.0354636579336078)*sj2)))),IkReal(((0.0279576637074784)+(((0.279961018819544)*sj2)))),IKFAST_ATAN2_MAGTHRESH);
if(!x194.valid){
continue;
}
IkReal x193=x194.value;
j1array[0]=((-1.0)*x193);
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
j1array[1]=((3.14159265358979)+(((-1.0)*x193)));
sj1array[1]=IKsin(j1array[1]);
cj1array[1]=IKcos(j1array[1]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
if( j1array[1] > IKPI )
{
    j1array[1]-=IK2PI;
}
else if( j1array[1] < -IKPI )
{    j1array[1]+=IK2PI;
}
j1valid[1] = true;
for(int ij1 = 0; ij1 < 2; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 2; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[1];
IkReal x195=IKcos(j1);
IkReal x196=IKsin(j1);
evalcond[0]=((((-0.0354636579336078)*sj2*x196))+(((-0.0490028456674111)*x196))+(((0.0279576637074784)*x195))+(((0.279961018819544)*sj2*x195)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
if( 1 )
{
bgotonextstatement=false;
continue; // branch miss [j0, j1]

}
} while(0);
if( bgotonextstatement )
{
}
}
}
}
}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
IkReal x197=((0.00200103)*cj2);
IkReal x198=((0.28019999)*sj2);
CheckValue<IkReal> x199=IKPowWithIntegerCheck(pz,-1);
if(!x199.valid){
continue;
}
CheckValue<IkReal> x200=IKPowWithIntegerCheck(((((0.02999885)*pz))+((pz*x197))+((pz*x198))),-1);
if(!x200.valid){
continue;
}
if( IKabs(((x199.value)*(((-0.02999885)+(((-1.0)*x198))+(((-1.0)*x197)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((x200.value)*(((0.00654364341690779)+(((0.0662969736252217)*sj2))+(((0.0785080302749392)*cj2*sj2))+(((0.00887956168449832)*cj2))+(((0.0011213771719794)*(cj2*cj2))))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr(((x199.value)*(((-0.02999885)+(((-1.0)*x198))+(((-1.0)*x197))))))+IKsqr(((x200.value)*(((0.00654364341690779)+(((0.0662969736252217)*sj2))+(((0.0785080302749392)*cj2*sj2))+(((0.00887956168449832)*cj2))+(((0.0011213771719794)*(cj2*cj2)))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j1array[0]=IKatan2(((x199.value)*(((-0.02999885)+(((-1.0)*x198))+(((-1.0)*x197))))), ((x200.value)*(((0.00654364341690779)+(((0.0662969736252217)*sj2))+(((0.0785080302749392)*cj2*sj2))+(((0.00887956168449832)*cj2))+(((0.0011213771719794)*(cj2*cj2)))))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x201=IKcos(j1);
IkReal x202=IKsin(j1);
IkReal x203=((0.00200103)*sj2);
IkReal x204=((0.28019999)*cj2);
IkReal x205=((0.28019999)*sj2);
IkReal x206=((0.00200103)*cj2);
IkReal x207=(pz*x201);
IkReal x208=(pz*x202);
evalcond[0]=((0.02999885)+x206+x205+x208);
evalcond[1]=((0.236820144868803)+(((-1.0)*x203))+x204+(((-1.0)*x207)));
evalcond[2]=((0.0215323265000576)+(((-1.0)*(pz*pz)))+(((-0.0599977)*x208))+(((0.473640289737606)*x207)));
evalcond[3]=((((0.236820144868803)*x202))+(((0.02999885)*x201))+((x201*x205))+((x201*x206))+(((-1.0)*x202*x203))+((x202*x204)));
evalcond[4]=((((-1.0)*x201*x204))+(((0.02999885)*x202))+((x201*x203))+pz+((x202*x206))+((x202*x205))+(((-0.236820144868803)*x201)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
CheckValue<IkReal> x210=IKPowWithIntegerCheck(pz,-1);
if(!x210.valid){
continue;
}
IkReal x209=x210.value;
CheckValue<IkReal> x211=IKPowWithIntegerCheck(x209,-2);
if(!x211.valid){
continue;
}
if( IKabs((x209*(((-0.02999885)+(((-0.00200103)*cj2))+(((-0.28019999)*sj2)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((6.25e-14)*x209*(((-788182559912.831)+(((-567902868206.972)*sj2))+(((33780910000000.0)*(x211.value)))+(((-4055641388.02502)*cj2)))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr((x209*(((-0.02999885)+(((-0.00200103)*cj2))+(((-0.28019999)*sj2))))))+IKsqr(((6.25e-14)*x209*(((-788182559912.831)+(((-567902868206.972)*sj2))+(((33780910000000.0)*(x211.value)))+(((-4055641388.02502)*cj2))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j1array[0]=IKatan2((x209*(((-0.02999885)+(((-0.00200103)*cj2))+(((-0.28019999)*sj2))))), ((6.25e-14)*x209*(((-788182559912.831)+(((-567902868206.972)*sj2))+(((33780910000000.0)*(x211.value)))+(((-4055641388.02502)*cj2))))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x212=IKcos(j1);
IkReal x213=IKsin(j1);
IkReal x214=((0.00200103)*sj2);
IkReal x215=((0.28019999)*cj2);
IkReal x216=((0.28019999)*sj2);
IkReal x217=((0.00200103)*cj2);
IkReal x218=(pz*x212);
IkReal x219=(pz*x213);
evalcond[0]=((0.02999885)+x216+x217+x219);
evalcond[1]=((0.236820144868803)+x215+(((-1.0)*x218))+(((-1.0)*x214)));
evalcond[2]=((0.0215323265000576)+(((-0.0599977)*x219))+(((0.473640289737606)*x218))+(((-1.0)*(pz*pz))));
evalcond[3]=(((x213*x215))+((x212*x216))+((x212*x217))+(((-1.0)*x213*x214))+(((0.236820144868803)*x213))+(((0.02999885)*x212)));
evalcond[4]=(((x213*x216))+((x213*x217))+(((-0.236820144868803)*x212))+((x212*x214))+pz+(((-1.0)*x212*x215))+(((0.02999885)*x213)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
CheckValue<IkReal> x220=IKPowWithIntegerCheck(IKsign(pz),-1);
if(!x220.valid){
continue;
}
CheckValue<IkReal> x221 = IKatan2WithCheck(IkReal(((-0.02999885)+(((-0.00200103)*cj2))+(((-0.28019999)*sj2)))),IkReal(((0.236820144868803)+(((-0.00200103)*sj2))+(((0.28019999)*cj2)))),IKFAST_ATAN2_MAGTHRESH);
if(!x221.valid){
continue;
}
j1array[0]=((-1.5707963267949)+(((1.5707963267949)*(x220.value)))+(x221.value));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x222=IKcos(j1);
IkReal x223=IKsin(j1);
IkReal x224=((0.00200103)*sj2);
IkReal x225=((0.28019999)*cj2);
IkReal x226=((0.28019999)*sj2);
IkReal x227=((0.00200103)*cj2);
IkReal x228=(pz*x222);
IkReal x229=(pz*x223);
evalcond[0]=((0.02999885)+x229+x227+x226);
evalcond[1]=((0.236820144868803)+x225+(((-1.0)*x224))+(((-1.0)*x228)));
evalcond[2]=((0.0215323265000576)+(((0.473640289737606)*x228))+(((-0.0599977)*x229))+(((-1.0)*(pz*pz))));
evalcond[3]=((((0.02999885)*x222))+((x222*x227))+((x222*x226))+((x223*x225))+(((-1.0)*x223*x224))+(((0.236820144868803)*x223)));
evalcond[4]=((((0.02999885)*x223))+((x222*x224))+(((-1.0)*x222*x225))+((x223*x226))+((x223*x227))+(((-0.236820144868803)*x222))+pz);
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}
}
}

}

}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
if( 1 )
{
bgotonextstatement=false;
continue; // branch miss [j0, j1]

}
} while(0);
if( bgotonextstatement )
{
}
}
}

} else
{
{
IkReal j1array[2], cj1array[2], sj1array[2];
bool j1valid[2]={false};
_nj1 = 2;
IkReal x230=((-0.236820144868803)+(((-0.28019999)*cj2))+(((0.00200103)*sj2)));
IkReal x231=((0.02999885)+(((0.00200103)*cj2))+(((0.28019999)*sj2)));
CheckValue<IkReal> x234 = IKatan2WithCheck(IkReal(x230),IkReal(x231),IKFAST_ATAN2_MAGTHRESH);
if(!x234.valid){
continue;
}
IkReal x232=((1.0)*(x234.value));
if((((x230*x230)+(x231*x231))) < -0.00001)
continue;
CheckValue<IkReal> x235=IKPowWithIntegerCheck(IKabs(IKsqrt(((x230*x230)+(x231*x231)))),-1);
if(!x235.valid){
continue;
}
if( ((pz*(x235.value))) < -1-IKFAST_SINCOS_THRESH || ((pz*(x235.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x233=IKasin((pz*(x235.value)));
j1array[0]=((((-1.0)*x232))+(((-1.0)*x233)));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
j1array[1]=((3.14159265358979)+(((-1.0)*x232))+x233);
sj1array[1]=IKsin(j1array[1]);
cj1array[1]=IKcos(j1array[1]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
if( j1array[1] > IKPI )
{
    j1array[1]-=IK2PI;
}
else if( j1array[1] < -IKPI )
{    j1array[1]+=IK2PI;
}
j1valid[1] = true;
for(int ij1 = 0; ij1 < 2; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 2; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];

{
IkReal j0eval[1];
j0eval[0]=((IKabs(px))+(((0.5)*(IKabs(py)))));
if( IKabs(j0eval[0]) < 0.0000000100000000  )
{
{
IkReal j0eval[1];
j0eval[0]=((((999.485265088479)*(IKabs((cj1*py)))))+(IKabs(((14.9917042722998)+(((499.74263254424)*cj1*px))+cj2+(((499.74263254424)*pz*sj1))+(((140.02788064147)*sj2))))));
if( IKabs(j0eval[0]) < 0.0000000100000000  )
{
{
IkReal j0eval[1];
j0eval[0]=((IKabs(((118.349122636244)+(((-499.74263254424)*cj1*pz))+(((-1.0)*sj2))+(((140.02788064147)*cj2))+(((499.74263254424)*px*sj1)))))+(((999.485265088479)*(IKabs((py*sj1))))));
if( IKabs(j0eval[0]) < 0.0000000100000000  )
{
{
IkReal evalcond[1];
bool bgotonextstatement = true;
do
{
evalcond[0]=((IKabs(px))+(IKabs(py)));
if( IKabs(evalcond[0]) < 0.0000050000000000  )
{
bgotonextstatement=false;
{
IkReal j0array[1], cj0array[1], sj0array[1];
bool j0valid[1]={false};
_nj0 = 1;
j0array[0]=0;
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
for(int ij0 = 0; ij0 < 1; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 1; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}
} while(0);
if( bgotonextstatement )
{
bool bgotonextstatement = true;
do
{
if( 1 )
{
bgotonextstatement=false;
continue; // branch miss [j0]

}
} while(0);
if( bgotonextstatement )
{
}
}
}

} else
{
IkReal op[2+1], zeror[2];
int numroots;
IkReal x236=((140.02788064147)*cj2);
IkReal x237=((1.0)*sj2);
IkReal x238=((499.74263254424)*cj1*pz);
IkReal x239=((499.74263254424)*px*sj1);
IkReal x240=((118.349122636244)+x236);
IkReal x241=(x238+x237);
op[0]=(x239+x240+(((-1.0)*x241)));
op[1]=((-999.485265088479)*py*sj1);
op[2]=((((-1.0)*x239))+x240+(((-1.0)*x241)));
polyroots2(op,zeror,numroots);
IkReal j0array[2], cj0array[2], sj0array[2], tempj0array[1];
int numsolutions = 0;
for(int ij0 = 0; ij0 < numroots; ++ij0)
{
IkReal htj0 = zeror[ij0];
tempj0array[0]=((2.0)*(atan(htj0)));
for(int kj0 = 0; kj0 < 1; ++kj0)
{
j0array[numsolutions] = tempj0array[kj0];
if( j0array[numsolutions] > IKPI )
{
    j0array[numsolutions]-=IK2PI;
}
else if( j0array[numsolutions] < -IKPI )
{
    j0array[numsolutions]+=IK2PI;
}
sj0array[numsolutions] = IKsin(j0array[numsolutions]);
cj0array[numsolutions] = IKcos(j0array[numsolutions]);
numsolutions++;
}
}
bool j0valid[2]={true,true};
_nj0 = 2;
for(int ij0 = 0; ij0 < numsolutions; ++ij0)
    {
if( !j0valid[ij0] )
{
    continue;
}
    j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];
htj0 = IKtan(j0/2);

_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < numsolutions; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
    }

}

}

} else
{
IkReal op[2+1], zeror[2];
int numroots;
IkReal x242=((140.02788064147)*sj2);
IkReal x243=((499.74263254424)*pz*sj1);
IkReal x244=((499.74263254424)*cj1*px);
IkReal x245=((14.9917042722998)+cj2+x243+x242);
op[0]=(x245+x244);
op[1]=((-999.485265088479)*cj1*py);
op[2]=(x245+(((-1.0)*x244)));
polyroots2(op,zeror,numroots);
IkReal j0array[2], cj0array[2], sj0array[2], tempj0array[1];
int numsolutions = 0;
for(int ij0 = 0; ij0 < numroots; ++ij0)
{
IkReal htj0 = zeror[ij0];
tempj0array[0]=((2.0)*(atan(htj0)));
for(int kj0 = 0; kj0 < 1; ++kj0)
{
j0array[numsolutions] = tempj0array[kj0];
if( j0array[numsolutions] > IKPI )
{
    j0array[numsolutions]-=IK2PI;
}
else if( j0array[numsolutions] < -IKPI )
{
    j0array[numsolutions]+=IK2PI;
}
sj0array[numsolutions] = IKsin(j0array[numsolutions]);
cj0array[numsolutions] = IKcos(j0array[numsolutions]);
numsolutions++;
}
}
bool j0valid[2]={true,true};
_nj0 = 2;
for(int ij0 = 0; ij0 < numsolutions; ++ij0)
    {
if( !j0valid[ij0] )
{
    continue;
}
    j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];
htj0 = IKtan(j0/2);

_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < numsolutions; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
    }

}

}

} else
{
IkReal op[2+1], zeror[2];
int numroots;
op[0]=py;
op[1]=((2.0)*px);
op[2]=((-1.0)*py);
polyroots2(op,zeror,numroots);
IkReal j0array[2], cj0array[2], sj0array[2], tempj0array[1];
int numsolutions = 0;
for(int ij0 = 0; ij0 < numroots; ++ij0)
{
IkReal htj0 = zeror[ij0];
tempj0array[0]=((2.0)*(atan(htj0)));
for(int kj0 = 0; kj0 < 1; ++kj0)
{
j0array[numsolutions] = tempj0array[kj0];
if( j0array[numsolutions] > IKPI )
{
    j0array[numsolutions]-=IK2PI;
}
else if( j0array[numsolutions] < -IKPI )
{
    j0array[numsolutions]+=IK2PI;
}
sj0array[numsolutions] = IKsin(j0array[numsolutions]);
cj0array[numsolutions] = IKcos(j0array[numsolutions]);
numsolutions++;
}
}
bool j0valid[2]={true,true};
_nj0 = 2;
for(int ij0 = 0; ij0 < numsolutions; ++ij0)
    {
if( !j0valid[ij0] )
{
    continue;
}
    j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];
htj0 = IKtan(j0/2);

_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < numsolutions; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
    }

}

}
}
}

}

}

} else
{
{
IkReal j0array[2], cj0array[2], sj0array[2];
bool j0valid[2]={false};
_nj0 = 2;
CheckValue<IkReal> x247 = IKatan2WithCheck(IkReal(((-1.0)*py)),IkReal(px),IKFAST_ATAN2_MAGTHRESH);
if(!x247.valid){
continue;
}
IkReal x246=x247.value;
j0array[0]=((-1.0)*x246);
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
j0array[1]=((3.14159265358979)+(((-1.0)*x246)));
sj0array[1]=IKsin(j0array[1]);
cj0array[1]=IKcos(j0array[1]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
if( j0array[1] > IKPI )
{
    j0array[1]-=IK2PI;
}
else if( j0array[1] < -IKPI )
{    j0array[1]+=IK2PI;
}
j0valid[1] = true;
for(int ij0 = 0; ij0 < 2; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 2; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
IkReal j1eval[3];
IkReal x248=cj2*cj2;
IkReal x249=(py*sj0);
IkReal x250=((1.0)*cj2);
IkReal x251=(cj0*px);
IkReal x252=(cj2*sj2);
IkReal x253=((140.02788064147)*sj2);
IkReal x254=((0.00200103)*cj2);
IkReal x255=(pz*sj2);
IkReal x256=((0.28019999)*sj2);
IkReal x257=(cj2*pz);
j1eval[0]=((((118.349122636244)*pz))+(((-1.0)*x250*x251))+(((-14.9917042722998)*x251))+(((-1.0)*x251*x253))+(((-1.0)*x249*x253))+(((-1.0)*x249*x250))+(((140.02788064147)*x257))+(((-14.9917042722998)*x249))+(((-1.0)*x255)));
j1eval[1]=IKsign(((((-0.02999885)*x251))+(((-1.0)*x251*x256))+(((-1.0)*x251*x254))+(((-0.02999885)*x249))+(((-1.0)*x249*x254))+(((-1.0)*x249*x256))+(((0.236820144868803)*pz))+(((0.28019999)*x257))+(((-0.00200103)*x255))));
j1eval[2]=((IKabs(((-0.00654364341690779)+(((-0.0662969736252217)*sj2))+((pz*x251))+(((-0.0011213771719794)*x248))+(((-0.00887956168449832)*cj2))+(((-0.0785080302749392)*x252))+((pz*x249)))))+(IKabs(((-0.0794119653973226)+(((-0.000120057197631)*cj2))+(((0.0785080302749392)*x248))+(((-0.0011213771719794)*x252))+(pz*pz)+(((-0.016811354940023)*sj2))))));
if( IKabs(j1eval[0]) < 0.0000010000000000  || IKabs(j1eval[1]) < 0.0000010000000000  || IKabs(j1eval[2]) < 0.0000010000000000  )
{
{
IkReal j1eval[3];
IkReal x258=cj2*cj2;
IkReal x259=(py*sj0);
IkReal x260=(cj0*px);
IkReal x261=(pz*sj2);
IkReal x262=(cj2*sj2);
IkReal x263=((140.02788064147)*cj2);
IkReal x264=((0.28019999)*cj2);
IkReal x265=((0.00200103)*sj2);
IkReal x266=((1.0)*pz);
j1eval[0]=((((-14.9917042722998)*pz))+(((-118.349122636244)*x259))+((sj2*x260))+(((-1.0)*x259*x263))+(((-1.0)*cj2*x266))+((sj2*x259))+(((-140.02788064147)*x261))+(((-118.349122636244)*x260))+(((-1.0)*x260*x263)));
j1eval[1]=IKsign(((((-0.28019999)*x261))+(((-0.236820144868803)*x260))+(((-0.00200103)*cj2*pz))+((x259*x265))+((x260*x265))+(((-1.0)*x259*x264))+(((-0.236820144868803)*x259))+(((-0.02999885)*pz))+(((-1.0)*x260*x264))));
j1eval[2]=((IKabs(((-0.00654364341690779)+(((-0.0662969736252217)*sj2))+(((-1.0)*x259*x266))+(((-0.0011213771719794)*x258))+(((-0.0785080302749392)*x262))+(((-0.00887956168449832)*cj2))+(((-1.0)*x260*x266)))))+(IKabs(((-0.0560877851367418)+(((0.0011213771719794)*x262))+(((-0.132714004448074)*cj2))+(((0.000947768428973642)*sj2))+(pz*pz)+(((-0.0785080302749392)*x258))))));
if( IKabs(j1eval[0]) < 0.0000010000000000  || IKabs(j1eval[1]) < 0.0000010000000000  || IKabs(j1eval[2]) < 0.0000010000000000  )
{
{
IkReal j1eval[2];
j1eval[0]=((-8.54155839473537)+(((-1.0)*sj2))+(((-8.37352017169531)*cj2)));
j1eval[1]=IKsign(((-0.135499750534064)+(((-0.0158635865110494)*sj2))+(((-0.132834061645705)*cj2))));
if( IKabs(j1eval[0]) < 0.0000010000000000  || IKabs(j1eval[1]) < 0.0000010000000000  )
{
continue; // no branches [j1]

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
IkReal x267=(cj0*px);
IkReal x268=((0.28019999)*sj2);
IkReal x269=(py*sj0);
IkReal x270=(cj2*pz);
IkReal x271=((0.00200103)*cj2);
IkReal x272=((0.28019999)*cj2);
IkReal x273=((0.00200103)*sj2);
CheckValue<IkReal> x274=IKPowWithIntegerCheck(IKsign(((-0.135499750534064)+(((-0.0158635865110494)*sj2))+(((-0.132834061645705)*cj2)))),-1);
if(!x274.valid){
continue;
}
CheckValue<IkReal> x275 = IKatan2WithCheck(IkReal(((((-0.236820144868803)*x267))+(((-0.236820144868803)*x269))+(((0.00200103)*x270))+(((-1.0)*x269*x272))+(((0.02999885)*pz))+((pz*x268))+(((-1.0)*x267*x272))+((x269*x273))+((x267*x273)))),IkReal(((((-1.0)*x269*x271))+(((-0.02999885)*x269))+(((-0.02999885)*x267))+(((-0.236820144868803)*pz))+(((-1.0)*x268*x269))+(((-1.0)*x267*x268))+(((-1.0)*x267*x271))+((pz*x273))+(((-0.28019999)*x270)))),IKFAST_ATAN2_MAGTHRESH);
if(!x275.valid){
continue;
}
j1array[0]=((-1.5707963267949)+(((1.5707963267949)*(x274.value)))+(x275.value));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x276=IKcos(j1);
IkReal x277=IKsin(j1);
IkReal x278=((0.00200103)*sj2);
IkReal x279=((0.00200103)*cj2);
IkReal x280=((0.28019999)*cj2);
IkReal x281=((0.28019999)*sj2);
IkReal x282=(cj0*px);
IkReal x283=(py*sj0);
IkReal x284=((1.0)*x282);
IkReal x285=(pz*x276);
IkReal x286=((1.0)*x283);
IkReal x287=(pz*x277);
IkReal x288=((0.0599977)*x276);
IkReal x289=((0.473640289737606)*x277);
evalcond[0]=((0.02999885)+(((-1.0)*x276*x286))+(((-1.0)*x276*x284))+x279+x287+x281);
evalcond[1]=((0.236820144868803)+(((-1.0)*x277*x286))+(((-1.0)*x277*x284))+x280+(((-1.0)*x285))+(((-1.0)*x278)));
evalcond[2]=((((-0.236820144868803)*x276))+(((-1.0)*x276*x280))+(((0.02999885)*x277))+pz+((x277*x279))+((x276*x278))+((x277*x281)));
evalcond[3]=((((-1.0)*x277*x278))+(((0.02999885)*x276))+(((-1.0)*x284))+(((-1.0)*x286))+((x276*x279))+(((0.236820144868803)*x277))+((x277*x280))+((x276*x281)));
evalcond[4]=((0.0215323265000576)+(((-1.0)*(px*px)))+(((-0.0599977)*x287))+(((0.473640289737606)*x285))+(((-1.0)*(pz*pz)))+(((-1.0)*(py*py)))+((x282*x289))+((x282*x288))+((x283*x289))+((x283*x288)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
IkReal x290=cj2*cj2;
IkReal x291=(cj2*sj2);
IkReal x292=(cj0*px);
IkReal x293=((0.28019999)*cj2);
IkReal x294=(py*sj0);
IkReal x295=((0.00200103)*sj2);
IkReal x296=((1.0)*pz);
CheckValue<IkReal> x297 = IKatan2WithCheck(IkReal(((-0.0560877851367418)+(((-0.132714004448074)*cj2))+(((0.000947768428973642)*sj2))+(pz*pz)+(((0.0011213771719794)*x291))+(((-0.0785080302749392)*x290)))),IkReal(((-0.00654364341690779)+(((-0.0662969736252217)*sj2))+(((-0.00887956168449832)*cj2))+(((-0.0785080302749392)*x291))+(((-1.0)*x294*x296))+(((-0.0011213771719794)*x290))+(((-1.0)*x292*x296)))),IKFAST_ATAN2_MAGTHRESH);
if(!x297.valid){
continue;
}
CheckValue<IkReal> x298=IKPowWithIntegerCheck(IKsign(((((-0.00200103)*cj2*pz))+(((-1.0)*x293*x294))+(((-0.28019999)*pz*sj2))+(((-0.236820144868803)*x294))+(((-0.236820144868803)*x292))+(((-0.02999885)*pz))+((x294*x295))+((x292*x295))+(((-1.0)*x292*x293)))),-1);
if(!x298.valid){
continue;
}
j1array[0]=((-1.5707963267949)+(x297.value)+(((1.5707963267949)*(x298.value))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x299=IKcos(j1);
IkReal x300=IKsin(j1);
IkReal x301=((0.00200103)*sj2);
IkReal x302=((0.00200103)*cj2);
IkReal x303=((0.28019999)*cj2);
IkReal x304=((0.28019999)*sj2);
IkReal x305=(cj0*px);
IkReal x306=(py*sj0);
IkReal x307=((1.0)*x305);
IkReal x308=(pz*x299);
IkReal x309=((1.0)*x306);
IkReal x310=(pz*x300);
IkReal x311=((0.0599977)*x299);
IkReal x312=((0.473640289737606)*x300);
evalcond[0]=((0.02999885)+x304+x302+x310+(((-1.0)*x299*x307))+(((-1.0)*x299*x309)));
evalcond[1]=((0.236820144868803)+(((-1.0)*x308))+x303+(((-1.0)*x300*x307))+(((-1.0)*x300*x309))+(((-1.0)*x301)));
evalcond[2]=(((x299*x301))+pz+(((-0.236820144868803)*x299))+(((-1.0)*x299*x303))+(((0.02999885)*x300))+((x300*x304))+((x300*x302)));
evalcond[3]=((((0.02999885)*x299))+((x299*x302))+((x299*x304))+(((0.236820144868803)*x300))+((x300*x303))+(((-1.0)*x300*x301))+(((-1.0)*x307))+(((-1.0)*x309)));
evalcond[4]=((0.0215323265000576)+((x305*x311))+((x305*x312))+(((-1.0)*(px*px)))+(((-0.0599977)*x310))+((x306*x312))+((x306*x311))+(((-1.0)*(pz*pz)))+(((0.473640289737606)*x308))+(((-1.0)*(py*py))));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
IkReal x313=cj2*cj2;
IkReal x314=(cj0*px);
IkReal x315=(cj2*sj2);
IkReal x316=(py*sj0);
IkReal x317=((0.00200103)*cj2);
IkReal x318=((0.28019999)*sj2);
CheckValue<IkReal> x319=IKPowWithIntegerCheck(IKsign(((((-0.00200103)*pz*sj2))+(((-0.02999885)*x316))+(((-0.02999885)*x314))+(((0.236820144868803)*pz))+(((-1.0)*x314*x317))+(((-1.0)*x314*x318))+(((-1.0)*x316*x317))+(((-1.0)*x316*x318))+(((0.28019999)*cj2*pz)))),-1);
if(!x319.valid){
continue;
}
CheckValue<IkReal> x320 = IKatan2WithCheck(IkReal(((-0.00654364341690779)+(((-0.0662969736252217)*sj2))+(((-0.0785080302749392)*x315))+(((-0.0011213771719794)*x313))+(((-0.00887956168449832)*cj2))+((pz*x316))+((pz*x314)))),IkReal(((-0.0794119653973226)+(((-0.000120057197631)*cj2))+(((0.0785080302749392)*x313))+(((-0.0011213771719794)*x315))+(pz*pz)+(((-0.016811354940023)*sj2)))),IKFAST_ATAN2_MAGTHRESH);
if(!x320.valid){
continue;
}
j1array[0]=((-1.5707963267949)+(((1.5707963267949)*(x319.value)))+(x320.value));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x321=IKcos(j1);
IkReal x322=IKsin(j1);
IkReal x323=((0.00200103)*sj2);
IkReal x324=((0.00200103)*cj2);
IkReal x325=((0.28019999)*cj2);
IkReal x326=((0.28019999)*sj2);
IkReal x327=(cj0*px);
IkReal x328=(py*sj0);
IkReal x329=((1.0)*x327);
IkReal x330=(pz*x321);
IkReal x331=((1.0)*x328);
IkReal x332=(pz*x322);
IkReal x333=((0.0599977)*x321);
IkReal x334=((0.473640289737606)*x322);
evalcond[0]=((0.02999885)+(((-1.0)*x321*x331))+(((-1.0)*x321*x329))+x332+x324+x326);
evalcond[1]=((0.236820144868803)+(((-1.0)*x323))+(((-1.0)*x322*x329))+x325+(((-1.0)*x330))+(((-1.0)*x322*x331)));
evalcond[2]=(((x322*x326))+((x322*x324))+(((-1.0)*x321*x325))+(((0.02999885)*x322))+pz+((x321*x323))+(((-0.236820144868803)*x321)));
evalcond[3]=(((x322*x325))+(((-1.0)*x329))+(((0.02999885)*x321))+(((-1.0)*x322*x323))+(((-1.0)*x331))+(((0.236820144868803)*x322))+((x321*x324))+((x321*x326)));
evalcond[4]=((0.0215323265000576)+(((-1.0)*(px*px)))+(((-0.0599977)*x332))+((x327*x334))+((x327*x333))+(((-1.0)*(pz*pz)))+((x328*x334))+((x328*x333))+(((-1.0)*(py*py)))+(((0.473640289737606)*x330)));
if( IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH  || IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(3);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}
}
}

}

}
}
}
}
return solutions.GetNumSolutions()>0;
}
static inline void polyroots2(IkReal rawcoeffs[2+1], IkReal rawroots[2], int& numroots) {
    IkReal det = rawcoeffs[1]*rawcoeffs[1]-4*rawcoeffs[0]*rawcoeffs[2];
    if( det < 0 ) {
        numroots=0;
    }
    else if( det == 0 ) {
        rawroots[0] = -0.5*rawcoeffs[1]/rawcoeffs[0];
        numroots = 1;
    }
    else {
        det = IKsqrt(det);
        rawroots[0] = (-rawcoeffs[1]+det)/(2*rawcoeffs[0]);
        rawroots[1] = (-rawcoeffs[1]-det)/(2*rawcoeffs[0]);//rawcoeffs[2]/(rawcoeffs[0]*rawroots[0]);
        numroots = 2;
    }
}
};


/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API bool ComputeIk2(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions, void* pOpenRAVEManip) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API const char* GetKinematicsHash() { return "<robot:GenericRobot - roarm_m2 (4b79c04bd812651ab2be6f5fac6f9719)>"; }

IKFAST_API const char* GetIkFastVersion() { return "0x1000004b"; }

#ifdef IKFAST_NAMESPACE
} // end namespace
#endif

#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>
#ifdef IKFAST_NAMESPACE
using namespace IKFAST_NAMESPACE;
#endif
int main(int argc, char** argv)
{
    if( argc != 12+GetNumFreeParameters()+1 ) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",GetNumFreeParameters());
        return 1;
    }

    IkSolutionList<IkReal> solutions;
    std::vector<IkReal> vfree(GetNumFreeParameters());
    IkReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    for(std::size_t i = 0; i < vfree.size(); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ComputeIk(eetrans, eerot, vfree.size() > 0 ? &vfree[0] : NULL, solutions);

    if( !bSuccess ) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }

    printf("Found %d ik solutions:\n", (int)solutions.GetNumSolutions());
    std::vector<IkReal> solvalues(GetNumJoints());
    for(std::size_t i = 0; i < solutions.GetNumSolutions(); ++i) {
        const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
        printf("sol%d (free=%d): ", (int)i, (int)sol.GetFree().size());
        std::vector<IkReal> vsolfree(sol.GetFree().size());
        sol.GetSolution(&solvalues[0],vsolfree.size()>0?&vsolfree[0]:NULL);
        for( std::size_t j = 0; j < solvalues.size(); ++j)
            printf("%.15f, ", solvalues[j]);
        printf("\n");
    }
    return 0;
}

#endif
